### ISSUE TITLE
Icons broken on upload screen

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#102]
Just saw this when testing on the ATLAS section

<img width="887" alt="image" src="https://user-images.githubusercontent.com/6764617/86114988-976f4280-bacb-11ea-9e5e-f17f351d9a14.png">

**Comment by 9inpachi** [comment]
This might be a temporary loading bug.
They seem to load fine on my side and on the deployed version as well.

![image](https://user-images.githubusercontent.com/36920441/86286910-c1765100-bc00-11ea-9675-76c555671765.png)

**Comment by EdwardMoyse** [comment]
Yep. Agreed.
