### ISSUE TITLE
Make it possible to scale jets / energies in general

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#103]
This should be something the user can tweak (in options, which we should also add) but also we should consider setting a sensible autoconfiguration ... the jets should never extend too far.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/6764617/86115269-02207e00-bacc-11ea-8e06-c42f0fe9b419.png">

**Comment by 9inpachi** [comment]
Hi Ed,

This is something I already did during the CMS integration.
Take a look at the code: https://github.com/9inpachi/phoenix/blob/wip-cms/src/app/services/loaders/objects/phoenix-objects.ts#L99-L102

**Comment by EdwardMoyse** [comment]
Ah cool! I think we should still make it possible for users to slide a scale - sometimes it's cool to make them look big, sometimes they get in the way (depending on the physics). But it could also just be in the configuration for the moment.

BTW is there any reason not to merge in your CMS WIP?

**Comment by 9inpachi** [comment]
> BTW is there any reason not to merge in your CMS WIP?

I am just polishing the code a little. It's all done. Will send a PR today.

About the CMS geometry. Would it be fine to use the one you shared with the Phoenix tasks?

**Comment by EdwardMoyse** [comment]
Yes, of course!
