### ISSUE TITLE
Add option to load geometry on demand

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#106]
Since geometry can be large, we should make it possible to conditionally load the geometry. i.e. have a placeholder in the menu, but only actually load the geometry when clicked on.

**Comment by 9inpachi** [comment]
Do you mean to load the geometry when we click on the "Geometry" group of dat.GUI? Or when we check the "Geometry -> Show" checkbox (will be disable by default)? Or to have the option in the UI menu?

**Comment by EdwardMoyse** [comment]
I think it should be per-piece of geometry. So we can define some geometry that is loaded immediately (show is on) whilst other stuff is in the menu, but not loaded by default. But when you click on it (click show), it appears.
