### ISSUE TITLE
How do you make the detector geometry?

### ISSUE THREAD

**Issue by tomeichlersmith** [HSF/phoenix#122]
Hello,

I am a developer for another physics experiment: [ldmx-sw](https://github.com/LDMX-Software/ldmx-sw), and I want to update our event display to something that uses Phoenix. How could I go about translating our detector geometry (which currently is hosted in a set of `gdml` files) into the files that are input to Phoenix? I poked around the repository, and it looks like the geometry files in the assets directories were generated by a computer some how.

Best,

Tom

**Comment by 9inpachi** [comment]
Hi @tomeichlersmith,

Phoenix supports most of the popular 3D formats on the web - which are `.obj`, `.gltf` and `.json`. We will also be supporting ROOT's `.root` and `.json.gz` file formats for loading detector geometries (see #117 for details on this). If you can get your geometry to any of these formats, you will be able to load them in Phoenix.

Having a really quick overview of `gdml` geometry format - it seems to be a part of `TGeoManager` and `Geant4` geometries. With my (little) understanding, TGeo classes are supported by JSROOT and can be accommodated inside `.root` files - which might be able to work with our current JSROOT support.

The things I am working on included a plan for supporting `Geant4` and `TGeo` geometries as well but given the other priorities it seems hard to do something in that regard for the moment - but I am positive we will be supporting them in due time.

Thanks.

**Comment by ric-bianchi** [comment]
Hi @tomeichlersmith and @9inpachi ,

About loading `gdml` files into three.js-based apps, I think @tpmccauley would be able to comment further and give you some suggestions.

Best,
-- Ric.

**Comment by EdwardMoyse** [comment]
ROOT supports GDML AFAIK, so I think this should be pretty easy once #117 is in.

Otherwise, Phoenix has many loaders already - I'm sure it would be technically feasible to add a GDML importer. It just might be a fair amount of work...

**Comment by tomeichlersmith** [comment]
Thank you all! I will focus on using the ROOT route, and default to writing my own `.json` if that doesn't work. Our detector geometry is simple compared to the other, larger HEP experiments.
