### ISSUE TITLE
Bug with Phoenix menu and collection info

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#128]
When I click on collection info, the highlight and focus/move camera icons aren't working correctly (they're offset)

![Aug-25-2020 16-10-00](https://user-images.githubusercontent.com/6764617/91185426-18267580-e6ee-11ea-9402-ca44e007ea1a.gif)

**Comment by 9inpachi** [comment]
I can reproduce this on my side.
Did you try it before and was it working fine then?

**Comment by EdwardMoyse** [comment]
Yes, it was working before. I'm seeing this in Chrome and Safari. How strange that you can't see it!

**Comment by 9inpachi** [comment]
It seems to work fine on the phone as well.
I am on the animations branch right now. I will try checking out master to see if the issue surfaces.
It might be a Mac specific issue otherwise.

**Comment by EdwardMoyse** [comment]
I'll try to test on a windows machine tonight.

**Comment by 9inpachi** [comment]
Cannot reproduce on the master branch either.

**Comment by EdwardMoyse** [comment]
Hmm. I don't see it in Firefox or Chrome on Windows, but I do see it in Safari and Chrome on mac. In firefox on mac it's also okay. There is another difference I see - when it works, the positions are wrapped. When it doesn't work, they extend to the right and I need to scroll to see them all.

**Comment by 9inpachi** [comment]
Able to reproduce this on my phone with chrome. Although it works fine on opera.

**Comment by EdwardMoyse** [comment]
This might be back... or at least, something is odd. Go to the  [deployed version](hepsoftwarefoundation.org/phoenix), choose ATLAS, then open the collection view and select InDetTrackParticles. I see:
![image](https://user-images.githubusercontent.com/6764617/92001096-8eeeee80-ed3e-11ea-980a-31c311de0c14.png)

**Comment by 9inpachi** [comment]
> This might be back... or at least, something is odd. Go to the deployed version, choose ATLAS, then open the collection view and select InDetTrackParticles.

I am pretty sure it's because of the debugging we were doing with RungeKutta where we limited the generation of tracks to 1 per collection. Exactly [THIS](https://github.com/HSF/phoenix/blob/master/src/app/services/loaders/phoenix-loader.ts#L281) line.

I refactored and fixed this with #135 

I see this with the latest version:

![image](https://user-images.githubusercontent.com/36920441/92002048-dbdfbe80-ed58-11ea-833d-c40a5062be8e.png)

**Comment by EdwardMoyse** [comment]
Hmm. I noticed something else here - only the tracks with the icons have uuids.

**Comment by EdwardMoyse** [comment]
Argh! I missed your comment above. Yes. You're right of course. Doh.
