### ISSUE TITLE
Cuts aren't initialised with the correct values

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#133]
They start as zero - they shoudl show the existing values.

![image](https://user-images.githubusercontent.com/6764617/91867095-8382c100-ec73-11ea-9474-06881bcc26cd.png)

**Comment by 9inpachi** [comment]
@EdwardMoyse just wanted to confirm. Is that how it worked before?

**Comment by EdwardMoyse** [comment]
I'm not sure this ever worked right, no. I just noticed that the track colour, and the cuts, are not set in the GUI as they are in the code.
