### ISSUE TITLE
Cuts not working after implementing pretty params

### ISSUE THREAD

**Issue by 9inpachi** [HSF/phoenix#144]
It seems using the pretty params directly as objects' `userData` causes cuts to not work.

Possible options are to

* Either put pretty params in a separate property of `userData` object
* Or use the new pretty param symbols as cut fields

Not sure which is more stable. For now I think we should go with putting pretty params inside a `userData` object property since it's something we process through the event display and not a raw part of event data.

**Comment by 9inpachi** [comment]
Fixed with f1a561dc98ec78a46a5a15e0f4b5429f711acdb7.
Will add it with the range slider I am working on.

**Comment by EdwardMoyse** [comment]
Cool!

Does this mean we couldn't have cuts on pretty parameters then? This would be a shame if so - it might be convenient to be able to cut on absolute momentum, for example, or pT.

**Comment by 9inpachi** [comment]
I think the new solution with the commit I mentioned is better. In it, we only get the pretty parameters when we need (for representation). For example, when we display it in the collection info or the selection overlay.

The actual parameters remain the same as they are in the event data.

**Comment by 9inpachi** [comment]
> Does this mean we couldn't have cuts on pretty parameters then? This would be a shame if so - it might be convenient to be able to cut on absolute momentum, for example, or pT.

We do have them. It's just that in general, the code will not use the pretty symbols - but the old alphabetical representation - so we have the parameters the same as they are in event data for the sake of consistency in code.
