### ISSUE TITLE
Save and load configuration

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#146]
It would be great if we could save and load the configuration of the Phoenix menus (what is shown, what colour etc etc)

As stage two, saving the camera locations would be great.

This would ultimately mean that the config could be loaded by the section, so developers could pre-configure a nice layout and have this loaded by Phoenix.

**Comment by 9inpachi** [comment]
Sounds interesting. I can say that Phoenix menu already maintains a menu state for each node - so with some tweaking and adaptation - it should work.

Setting up scene related configuration should be easy.

May be I will take a look this weekend. ;)

**Comment by 9inpachi** [comment]
Will work on it to save camera position as well. Just can't think of a good way to do it since we can't access the event display directly from a Phoenix menu node.

**Comment by 9inpachi** [comment]
Implemented with #148 and #159.
