### ISSUE TITLE
DISCUSSION: Commit messages for changelogs

### ISSUE THREAD

**Issue by 9inpachi** [HSF/phoenix#147]
This discussion is about making commit messages follow a convention. The reason is changelogs for releases. For example, changelogs using lerna are generated like [THIS](https://github.com/babel/babel/blob/main/CHANGELOG.md) for babel. Looks like they have a [custom configuration](https://github.com/babel/babel/blob/main/lerna.json#L3-L17) for using labeled PRs as changelogs.

These changelogs are generated separately for each package and one is generated in the root directory of the repository combining changelog of all packages. And there isn't really an option to skip changelog generation ([the release command](https://github.com/lerna/lerna/tree/master/commands/version#--create-release-type) requires the `--conventional-commits` option).

It seems that for automatic changelog generation (like the one we have generated [CHANGELOG.md](https://github.com/HSF/phoenix/blob/master/CHANGELOG.md)) using lerna, we need to follow some kind of predefined pattern for commit messages to mark them as docs, fixes or features (and others).

For now I am using `raw-git-commit` ([configured here](https://github.com/HSF/phoenix/blob/master/lerna.json#L15)) which uses raw commit messages as changelogs for each package. But I think we should choose a pattern and use that throughout and make it a standard for the repository just to generate pretty and well written changelogs for each release (like three.js).

Angular changelogs are generated like [THIS](https://github.com/angular/angular/blob/master/CHANGELOG.md). We can use [the Angular commit conventions](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular) or some other from [HERE](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages) (we are using `raw-git-commits` package from here).

Although at the end, I am not sure if it will be too much of a hassle / barrier for potential contributors to follow standards like this.

WDYT?

**Comment by EdwardMoyse** [comment]
Sorry for taking so long. I do worry a little that this might be a bit of extra work, but it does look very nice and I think as long as we document it well, it shouldn't be a big problem for contributors.

I'm fine with the Angular commit convention - in the end I think the most important thing is to have something simple, but fairly flexible. They seem to match this requirement. We would just have to agree on a list of subheaders (which I think should be <10 to keep it manageable)

**Comment by EdwardMoyse** [comment]
Following on from this, if we take the angular convention, how about this:
```
<type>(<scope>): <short summary>
  │       │             │
  │       │             └─⫸ Summary in present tense. Not capitalized. No period at the end.
  │       │
  │       └─⫸ Commit Scope: app-atlas | app-cms | app-lhcb | app-trackml | app-playground | app-ui | app-menu | ed-extras | ed-helpers | ed-loaders | ed-tests | ed-three | ed-ui
  │
  └─⫸ Commit Type: build|ci|docs|feat|fix|perf|refactor|style|test
```

Another option would be to keep the commit-scope very simple and have just ` app | event-display` and then rely on the summary for context (I think I probably prefer this).

**Comment by 9inpachi** [comment]
Oh yes. I was thinking of adding this to the contribution guidelines but couldn't get the time.

I think it's best if we go with the simpler scope(s) you propose. Having only the app and event-display will be better.

And we can further simplify the type as well and use only 4-5 types like `feat | fix | docs | style | build`. I don't think we need that many. We can add a `misc` type for miscellaneous changes.

**Comment by EdwardMoyse** [comment]
Okay, perfect.

I want to do some documentation changes today, so I'll add this.
