### ISSUE TITLE
Issues with Phoenix in VR

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#151]
There are two problems that I've spotted so far:

- no 6 DOF (ideally we would be able to walk around)
- performance is *terrible* ... it's 2 or 3 frames per second I think, and there are lots of clipping issues.

I suspect the first is solvable... the second might be hard, though I don't think our scene is particularly complicated compared to others I've seen which work really well.

Anyway, not the top priority, but just to keep note of it.

**Comment by 9inpachi** [comment]
> no 6 DOF (ideally we would be able to walk around)

I don't quite get this. Can you elaborate a little?

> performance is terrible ... it's 2 or 3 frames per second

What device are you on?
Even on my phone with relatively low end integrated graphics (Adreno 509), I get about 30 FPS inside the detector and 50-60 FPS outside it.

> there are lots of clipping issues

Can you share some screenshots of this?

**Comment by EdwardMoyse** [comment]
> > no 6 DOF (ideally we would be able to walk around)
> 
> I don't quite get this. Can you elaborate a little?

Simpler VR headsets (and phones) can only measure orientation (3 degrees of freedom). 

The Rift/Quest etc can also measure position (6 DOF / degrees of freedom) but this isn't being used by Phoenix. I need to check if other threejs demos permit this, but certainly other WebXR demos do.

> 
> > performance is terrible ... it's 2 or 3 frames per second
> 
> What device are you on?
> Even on my phone with relatively low end integrated graphics (Adreno 509), I get about 30 FPS inside the detector and 50-60 FPS outside it.

It's a Quest2, so pretty powerful (it has an XR2 - the most powerful mobile android chipset at the moment I believe )

> > there are lots of clipping issues
> 
> Can you share some screenshots of this?

I'll try - I need to work out how to get them off of the quest. But it's very bad - it's like the depth sorting isn't really working.

**Comment by 9inpachi** [comment]
>It's a Quest2, so pretty powerful (it has an XR2 - the most powerful mobile android chipset at the moment I believe )

There shouldn't be any performance issues then. The only thing I can think of is that the main renderer doesn't get stopped so both VR renderer and the main renderer are running at the same time which can cause a drop in performance, but still not something of this degree. Not sure how to debug it without a device at hand. :(

**Comment by EdwardMoyse** [comment]
I'll try to find some time to investigate a bit more myself. It is very odd - even though it's rendering twice (one per eye) it shouldn't drop from >60FPS to <10 FPS. Though perhaps it's a combination of what you suggest and the double rendering... It will be interesting to see if there is any advice out there of how to debug this.

**Comment by 9inpachi** [comment]
Let me check, the chrome debugging extension might have an option to select Quest2 as the device.

**Comment by 9inpachi** [comment]
So yes. I can reproduce this with the "Oculus Quest". I get about 20-30 FPS.

Does the scene look similar to this?

![image](https://user-images.githubusercontent.com/36920441/96289526-a9cfa680-0ffe-11eb-8b35-a9da66865d34.png)

**Comment by EdwardMoyse** [comment]
Well, it's even worse (random triangles clipping through) but yes similar.

**Comment by 9inpachi** [comment]
And somehow it looks fine on phone.

![Screenshot_20201016-223247](https://user-images.githubusercontent.com/36920441/96290342-df28c400-0fff-11eb-846d-4ae2dcf18b67.jpg)

I will debug it and follow up here. Let me know if you find something on your end.

**Comment by 9inpachi** [comment]
Finally found the bug. It's because of the wretched `EffectComposer`!
I have a fix prepared, I will refine it tomorrow.

**Comment by EdwardMoyse** [comment]
Hi @9inpachi - amazing that you found it! I look forward to seeing what it was.

**Comment by 9inpachi** [comment]
Hi @EdwardMoyse You can check the fix from [fix-vr](http://github.com/9inpachi/phoenix/tree/fix-vr) and let me know if it works.

**Comment by EdwardMoyse** [comment]
I tried what you have in `fix-vr` - I can confirm it seems to fix the glitching. Unfortunately it's still very, very slow.

**Comment by 9inpachi** [comment]
I have no idea why it's so slow. May be debugging it on the device will help. The current render we do for VR is the minimal one. I don't think we can process anything less than what we are processing now.

**Comment by EdwardMoyse** [comment]
Hi @9inpachi - I've managed to get some performance measurements from running Firefox reality on the Quest. FPS is pretty low even outside of VR, so perhaps this isn't VR-specific (it's just it's much more noticeable there)

I attach three:
- threejs - this is the vr/dragging example
- phoenix - ATLAS rotating not in VR 
- phoenixVR - ATLAS rotating, in VR

I have to say I need to learn a lot more about how to interpret these profiles, but nothing leaps out at me.


[PhoenixProfiles.zip](https://github.com/HSF/phoenix/files/5402816/PhoenixProfiles.zip)

**Comment by EdwardMoyse** [comment]
Okay, forget all of this - I worked out how to debug using Oculus Browser, and .... there the performance is *excellent*. So, it seems to be limited to Firefox Reality and the fix is just we recommend Oculus Browser.

**Comment by EdwardMoyse** [comment]
(But please push `fix-vr` when you get a chance!)
