### ISSUE TITLE
App Deployment: make it possible to modify routes on deployment

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#163]
The idea would be to be able to modify Phoenix on deployment so that only one component is shown
i.e. 
change a URL like:
http://phoenixatlas.web.cern.ch/PhoenixATLAS/#/atlas

to:
http://phoenixatlas.web.cern.ch/PhoenixATLAS/#/

i.e. the route would be modified to be (in this case):
```
const routes: Routes = [
  { path: '', component: AtlasComponent }
]
```

**Comment by EdwardMoyse** [comment]
And I think we can probably disable the `useHash` at the same time?

**Comment by 9inpachi** [comment]
How about we make it a part of #149? Have a single route for this and supplying an event (through some kind of configuration file) will load it with that event.
