### ISSUE TITLE
Use object to simplify configuration

### ISSUE THREAD

**Issue by 9inpachi** [HSF/phoenix#165]
We should use a single JavaScript object and simplify the configuration. Right now we have a class and we create an object and pass it to the event display which is unnecessarily complex and I don't think it's the right way since we don't need any class functions in our case.

As a practical example.

**Current flow:**

```ts
// Configuration(elementId?: string, enableDatGUIMenu?: boolean)
const configuration = new Configuration('eventDisplay', true);
// Preset views
configuration.presetViews = [
  new PresetView('Left View', [0, 0, -12000], 'left-cube'),
  new PresetView('Center View', [-500, 12000, 0], 'top-cube'),
  new PresetView('Right View', [0, 0, 12000], 'right-cube')
];
// Default view
configuration.defaultView = [4000, 4000, 4000];
// Root Phoenix menu node
configuration.setPhoenixMenuRoot(this.phoenixMenuRoot);
```

**Proposed/updated flow:**

What we could or should do using a simple JS object. Instead of setting each configuration individually, we can do it all at once using an object or some individually if we want.

```ts
const configuration: Configuration = {
  elementId: 'eventDisplay', // optional
  enableDatGUIMenu: true, // optional
  defaultView: [4000, 4000, 4000],
  phoenixMenuRoot: this.phoenixMenuRoot,
  presetViews: [
    new PresetView('Left View', [0, 0, -12000], 'left-cube'),
    new PresetView('Center View', [-500, 12000, 0], 'top-cube'),
    new PresetView('Right View', [0, 0, 12000], 'right-cube')
  ]
};
```

WDYT?

**Comment by EdwardMoyse** [comment]
I was actually thinking something similar when I was working on the default view, so definite +1 from me!
