### ISSUE TITLE
Make it possible to add geometry to a folder

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#171]
For example, I would like to be able to do:
```TypeScript
    this.eventDisplay.loadGLTFGeometry('ITK.gltf', 'Beam', "Inner Detector",1000);
    this.eventDisplay.loadGLTFGeometry('TRT.gltf', 'Beam', "Inner Detector",1000);
```
And have both of these appear under an Inner Detector sub-folder.

**Comment by 9inpachi** [comment]
I would like to implement this generically with the ability to specify a node in the Phoenix menu to add this to. 
Not sure how to do that right now. But I'll think about it.

**Comment by 9inpachi** [comment]
So I am thinking of a separator if we want to insert our geometry into a multilevel hierarchy. For example, "Inner Detector>More Inner Detector" will put the geometry inside the "More Inner Detector" folder which will be inside "Inner Detector" folder and the separator is `>`. Is this separator good?
We can also use `.` or `:` as a separator. Not sure which will work better.

**Comment by EdwardMoyse** [comment]
That’s a good idea! I think > is fine (as are the others!)

We could presumably make more than one sub-menu this way too ... but then
it would probably make more sense to reverse the order i.e.

SubMenuLevel1 > SubMenuLevel2 > MenuItem

?

**Comment by 9inpachi** [comment]
> SubMenuLevel1 > SubMenuLevel2 > MenuItem

Not sure about this. For me, as a normal user, this looks anti intuitive. I would expect the order to be as top to bottom hierarchy. Do people you work with prefer the reverse order?

**Comment by EdwardMoyse** [comment]
Sorry I think I misread your initial message and actually we agree! 

Just to check, taking Pixels as a concrete example, as a user the top level menu item you see is Geometry and then you would open Inner Detector and the finally click on Pixels to visualise them.

So, since Geometry is implied, this would become:
```TypeScript
    this.eventDisplay.loadGLTFGeometry('Pixels.gltf', 'Inner Detector>Pixels',,1000);
```

And if we had more details to visualise it could be e.g.
```TypeScript
    this.eventDisplay.loadGLTFGeometry('Pixels_Layer1.gltf', 'Inner Detector>Pixels>Pixel Layer 1',,1000);
```

**Comment by 9inpachi** [comment]
Yes Ed, exactly.
