### ISSUE TITLE
Add ability to load a "label" file

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#172]
This is going to take a bit of thinking about ... but here are a few usecases to illustrate the point:
1. we want to be able to "decorate" Calorimeter cells with calibration information (and then possibly colour them differently, depending on the information)
2. we want to be able to identify two tracks as a positive and negative muon, as determined by the reconstruction and then add a label to the tracks in the event display
3. we want to be able to label some tracks and jets, as e.g "leading", "subleading"  and show this in the display to be able to match to a description of the event. (See attached picture for an example of this one)

It seems to me that we could easily add these to the JSON (perhaps with a new "label" key), however this will be harder for non-Phoenix formats such as JiveXML, root, or iSpy.

So instead I was thinking instead we could make it general... i.e. you can load a separate JSON file which is a bunch of labels, and then optionally display them in the display.

Perhaps the first stage could be to think of a way to add labels to objects from within Phoenix, and then save these label files? This way we would solve the format, and the UI.

For the format, I was thinking that it would need to `"Label Text" : "Type/Container Name/Position in Container"`

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/6764617/99083565-00141300-25c6-11eb-8dcf-3239a7265342.png">

**Comment by 9inpachi** [comment]
Okay, I just understood this. Previously I thought you meant to attach these labels to individual event data objects so it seemed hard.

Adding labels with a JSON file should be simple. One thing could be to add labels and generate the JSON file from within Phoenix (would be a little complex and not so flexible).

**Comment by EdwardMoyse** [comment]
Sorry @9inpachi for the delayed response.

I *do*  kind of mean adding labels to individual objects. So example, imagine you have 100 tracks in a container in a file. You could load the event data, and then afterward load `labels.json` and loop through this adding `Label` attributes to the tracks.

We could start by adding a `add label` button to the container view which would add the decoration to the object, and show it in 3D:

![image](https://user-images.githubusercontent.com/6764617/102463937-03c70980-404c-11eb-98ba-36fbeda7bce4.png)

(obviously the 'icon' is just to show the idea - it should be a button similar to the others with a quote inside)
