### ISSUE TITLE
Tracks hide vertices when we zoom in

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#178]
When we zoom in, the tracks are rendered as cylinders of fixed size and so they obscure the vertex (in the attached picture, there is a primary vertex from which most of the tracks are coming).

I think we should add an option for how to render tracks e.g.
  - Auto : use  [THREE.LOD](https://threejs.org/docs/index.html#api/en/objects/LOD) to determine how to render, but with line for close and cylinder for far away. The issue here will be that LOD is presumably calculated from the centre of the object, which might well not work well with long tracks.
  - Line : force line only
  - Cylinder : force cylinder always (and  let the user choose the diameter)

We could add the option first, and then Auto after, since then we could play with rendering options more easily.

This will also be very useful for highlighting some tracks -  you could make this collection thicker, so they stand out.

![image](https://user-images.githubusercontent.com/6764617/99646595-f9b3ea00-2a50-11eb-80b7-a9993bb6be09.png)

**Comment by 9inpachi** [comment]
The implementation I just did for this hides the tube geometry when the camera is at a radius less than 200.

See: https://github.com/9inpachi/phoenix/commit/7d606b29214e9f080266ad13502fa1092605a00f

Is this approach okay by you?
