### ISSUE TITLE
Colour tracks by the vertex to which they are associated.

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#179]
Vertices know the tracks which were involved in their reconstruction. It should be possible to colour these tracks the same colour as the vertex.

(This is low priority, but just to put it out as an option).

**Comment by 9inpachi** [comment]
![image](https://user-images.githubusercontent.com/36920441/116449002-25929180-a873-11eb-84df-05e9fc8ba23e.png)

Do the "linkedTracks" point to tracks by index in event data?

**Comment by EdwardMoyse** [comment]
Yes.

**Comment by 9inpachi** [comment]
Closed with #298
