### ISSUE TITLE
Travis, snyk, coveralls.io etc tests failing 

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#18]
This is because they still point to emilio's fork.

**Comment by emiliocortina** [comment]
For coverage badges, we would have to get permission from the HSF organization.

**Comment by ric-bianchi** [comment]
Hi @emiliocortina , I had the green light from the HSF coordinators, so I can set the needed permissions. I'll do that ASAP. Sorry for the delay...

**Comment by ric-bianchi** [comment]
P.S. @emiliocortina , if I forget, please remind that to me in a few days... ;)
