### ISSUE TITLE
How to import ROOT files?

### ISSUE THREAD

**Issue by vvolkl** [HSF/phoenix#184]
The user manual https://github.com/HSF/phoenix/blob/master/guides/users.md#geometry mentions root files with tgeo are supported, however the import dialog only has buttons for .obj and gltf.
Thanks!

**Comment by 9inpachi** [comment]
Hi @vvolkl 

The "Phoenix event display" framework supports loading ROOT geometries. So you have to load the geometry through code. For example.

See [docs for `loadRootGeometry`](https://hepsoftwarefoundation.org/phoenix/api-docs/classes/EventDisplay.html#loadRootGeometry).

```ts
const config = {};
const eventDisplay = new EventDisplay(config);

ScriptLoader.loadJSRootScripts((JSROOT) => {
  eventDisplay.loadRootGeometry(JSROOT, 'path/to/file.root', 'obj;1', 'ROOT GEOMETRY', 1, true);
});
```

We do it like [THIS](https://github.com/HSF/phoenix/blob/master/packages/phoenix-ng/projects/phoenix-app/src/app/sections/cms/cms.component.ts#L34-L36) for the CMS experiment. We use the JSON geometry here but we also have the function `EventDisplay.loadRootGeometry` to load a "root" file.

**Comment by EdwardMoyse** [comment]
Hi @vvolkl - please let us know if this doesn't work or if you are still having problems? 

We probably should add all supported geometries to the dialog it's true.

**Comment by 9inpachi** [comment]
> We probably should add all supported geometries to the dialog it's true.

Yes - same opinion.

**Comment by vvolkl** [comment]
@9inpachi  @EdwardMoyse Thanks for the quick reply! The code you provided looks good, but I haven't yet had time to install all the npm things on my system, will try this afternoon.

Indeed it would be nice to be able to quickly try out different detectors without having to fire up a server instance locally. JSROOT allows you to pass options via the url, that could also be a simple way to allow this:

https://root.cern/js/latest/?nobrowser&json=../files/geom/simple_alice.json.gz&file=../files/geom/tracks_hits.root&item=simple_alice.json.gz+tracks_hits.root/tracks;1+tracks_hits.root/hits;1

**Comment by 9inpachi** [comment]
We have options to load the event from URL yet but not the geometry. The project is still in progress so may be it will be supported in next versions (we don't have a definitive roadmap yet).

**Comment by 9inpachi** [comment]
> We probably should add all supported geometries to the dialog it's true.

I just realized that we need to specify the object for the ROOT geometry so the process is not as straightforward as just importing the file.
