### ISSUE TITLE
Generalise the colouring of object

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#185]
This is a generalisation of #179 

In VP1 we can do things like colour :
- tracks by associated vertex, charge, pT etc
- hits by the associated tracks, charge etc
- clusters by energy
- jets by vertex

It would be good to think of a general, extensible way to do this within Phoenix.

**Comment by 9inpachi** [comment]
Ed, can you show me a screenshot or better a GIF / video of how the UI works in VP1?
I am not sure where to include these options and how to manage them.

**Comment by EdwardMoyse** [comment]
Hi @9inpachi - sorry, I thought I'd replied ages ago (I think I replied to the email and this apparently didn't post here).

I don't know if this is clear enough, but there is some documentation here:
http://atlas-vp1.web.cern.ch/atlas-vp1/doc/doc_tracksysbasics/

The video does show how this works for tracks. We also added since then, 'colour by vertex' .. so all tracks associated to avertex would be coloured by the vertex colour. This means we'd need to add random vertex colouring, OR, even better, making it possible (in the collections view) to colour specific objects by hand. This could be very useful for highlighting specific tracks, vertices, clusters etc.

**Comment by 9inpachi** [comment]
I just saw the video (after converting it to mp4). That's an interesting UI to go by. Where do you think we should place it? In a dialog opened through the UI menu or handle it entirely in the Phoenix menu? The latter gives us the option for saving/loading state.

**Comment by 9inpachi** [comment]
Hi @EdwardMoyse

I am wondering if these options should be collection-wise in the Phoenix menu? From the video - it seems they were for all collections of tracks. We don't currently have a way to add specific options to individual collections.

![image](https://user-images.githubusercontent.com/36920441/115144153-85fc2480-a064-11eb-8f99-6c29303a26a1.png)

This is the UI I have so far.

**Comment by EdwardMoyse** [comment]
Hi Fawad,
It would definitely be better to colour by collection - colouring all track collections the same way isn't likely to be what users will want.

However, it's definitely better than nothing, so if this is all we can do for now, then that's fine.

Colouring objects is honestly one of the things we found hardest in VP1. When we next chat I can explain some of it.

**Comment by 9inpachi** [comment]
> Colouring objects is honestly one of the things we found hardest in VP1.

I can surely understand why. It does seem more useful to do with collections. I'll try finding a (good) way.

**Comment by 9inpachi** [comment]
@EdwardMoyse

Is this the right UI for coloring by momentum? (The range slider and below that)
And also what unit do we have in our data? Is it `GeV` or `MeV` or something lower?

![image](https://user-images.githubusercontent.com/36920441/115152592-25341280-a08b-11eb-92b9-fa5924b3f5eb.png)

**Comment by 9inpachi** [comment]
The general functionality is implemented with support for some event data types. If there needs to be support for more types, open a new issue. ;)
