### ISSUE TITLE
Loading from state is not working correctly

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#187]
I tried to add a default configuration for ATLAS, but it isn't working correctly:
https://github.com/EdwardMoyse/phoenix/blob/add-atlas-default-config/packages/phoenix-ng/projects/phoenix-app/src/app/sections/atlas/atlas.component.ts#L74

specifically, some jet collections should be disabled, and the pixel and SCT hits should be different colours to red.

When you choose 'Load State' from the menu, then it works as expected.

**Comment by 9inpachi** [comment]
Yup, expected.

You have to make `ngOnInit` async and await for the geometry loading functions. See [FASER code](https://github.com/joshmcfayden/phoenix/blob/mcfayden_faser_v1/packages/phoenix-ng/projects/phoenix-app/src/app/sections/faser/faser.component.ts#L19-L67).

**Comment by EdwardMoyse** [comment]
Ah ha! Thanks! However there is still a problem - the menu items state are not updated - for example, two Jet collections should be disabled here:
<img width="704" alt="image" src="https://user-images.githubusercontent.com/6764617/101160992-33c7e300-3630-11eb-81d7-176c84c8dfa6.png">

**Comment by 9inpachi** [comment]
Does this new bug work fine with loading state from the menu?

**Comment by 9inpachi** [comment]
I forgot to put it earlier, but we could also load state from code after all the loading is done ([see here](https://github.com/HSF/phoenix/blob/master/packages/phoenix-ng/projects/phoenix-app/src/app/sections/atlas/atlas.component.ts#L75)).

**Comment by EdwardMoyse** [comment]
> 
> 
> Does this new bug work fine with loading state from the menu?

No. Same issue when loading state from the menu. I like the idea of doing it once loading is done though!

**Comment by 9inpachi** [comment]
> No. Same issue when loading state from the menu

Ok, then I will have to look into the export and import state functions. I will give news tonight maybe.

**Comment by 9inpachi** [comment]
> No. Same issue when loading state from the menu. I like the idea of doing it once loading is done though!

Indeed. The loading manager is pretty cool I think.

**Comment by 9inpachi** [comment]
So @EdwardMoyse,

The file you exported is wrong.

For the file https://github.com/EdwardMoyse/phoenix/blob/add-atlas-default-config/packages/phoenix-ng/projects/phoenix-app/src/assets/files/config/atlas-config.json
If you search for `Anti` to see the configuration for the Jet collections, you will see that the `toggleState` is `true` for all so it's expected that they will show.

I tried exporting to see if it's a problem with export but my export works fine and I can also import the same file with disabled / hidden Jets collections without a problem.

**Comment by 9inpachi** [comment]
From #188

![image](https://user-images.githubusercontent.com/36920441/101210624-9e603980-3697-11eb-9d7e-af64cceacf4a.png)

**Comment by EdwardMoyse** [comment]
Whoops - you were right ... however in my local tests I *was* using a file with the correct configuration (not for the final check of loading from the menu, obviously!). 

For reasons I don't quite understand, using the loading Manager fixes it! So I think this can be closed now.
