### ISSUE TITLE
Add a new 'Playground' tab to the nav

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#19]
This should be blank, with options to load (and remove) arbitrary OBJ geometry, plus (eventually) event data.

Change colour would be great.

Also, shift in space? i.e. load a piece of shielding material and move to -20m from the origin.

**Comment by emiliocortina** [comment]
Playground section added in 9e2bea049e9b310eaf989adb23a6ca70d7d8e309
with color picker in 9e06ce3267ce7326e4506bbcbc825f108e4e90a1 and moving OBJ geometries in https://github.com/HSF/phoenix/commit/9e841576c1f0af23a353a03737083e6836938be0
