### ISSUE TITLE
Add staging area

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#190]
It should be possible (I think!) to make PRs publish to a staging area where we can test the changes interactively.

Obviously not top priority, but it would be convenient!

**Comment by 9inpachi** [comment]
+1

That'd be interesting. I never implemented something like this so I will have to see the right approach. Having it on the repo itself could prove problematic I think.

**Comment by EdwardMoyse** [comment]
We have something similar set up here:

https://gitlab.cern.ch/atlas-sw-git/atlassoftwaredocs

(I hope you can open it) Every PR creates a directory in __staging with a
new version of the webpage. I presume we should be able to do this too in
GitHub.

**Comment by 9inpachi** [comment]
Can't access it. I will try looking for other resources and see what I can
find. Doing it through GitHub is easily manageable but I hope it doesn't
overcomplicate things on the build side.

**Comment by 9inpachi** [comment]
So I looked into the following options.

* Surge
  * https://surge.sh/ - Good for one time publishing but requires custom set up for PRs and such. (https://medium.com/onfido-tech/travis-surge-github-auto-deploy-every-pr-branch-and-tag-a6c8c790831f)
* Tugboat
  * https://tugboat.qa/ - Specifically for publishing websites with PRs. Takes care of the URL naming and everything. 2 GB free space. Requires org admins to allow access to the repository and add the repository in tugboat like travis.

I already implemented using tugboat and here's a view of my [master](https://github.com/9inpachi/phoenix/tree/master) branch: https://master-bsxar1erwschfonhvwa1ue9x6wdfbjln.tugboat.qa/

@EdwardMoyse Do you have any comments or suggestions?

**Comment by 9inpachi** [comment]
A third option would be to keep everything on GitHub. Move the current deployment set up to the `gh-pages` branch. Then have a sub folder in the branch like `gh-pages/pr-119` and have it manually updated through travis. Will take some effort.

**Comment by 9inpachi** [comment]
Here are some notes for doing it on GitHub.

```
When pushed to master. We want to

- build the app
- push the build to gh-pages

Complications with PRs.

Let's say through a travis workflow.

- we build a PR
- checkout the gh-pages branch
- add a folder for the PR
- commit and push the changes to the gh-pages branch

BUT

When we do that, we get a different commit history in gh-pages. So if we try to build the app from master and push the subtree to gh-pages, the commit history is changed with PR related things and the push can't be done without force.

Workaround

For each release, force push to gh-pages resetting the history and removing all the folders of PR.
```

**Comment by 9inpachi** [comment]
Closing with #196.

**Comment by 9inpachi** [comment]
A single preview build takes the entire 2 GB for some reason.
Reopening this issue so that we follow up.
