### ISSUE TITLE
For playground, make it possible to save the configuration

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#20]
Once we can load OBJ files and colour them, and move them around, it woudl be great to be able to save the configuration and load it back again. Or write out a new phoenix component, to help people making a new ED.

**Comment by emiliocortina** [comment]
Import options added in 8b92403ff6cd967ca6a36a323081706576e1a006 and export option in 405d8379610d09b6d391728221fb6a367d50ff88
