### ISSUE TITLE
Use JSROOT from some external source

### ISSUE THREAD

**Issue by 9inpachi** [HSF/phoenix#204]
Currently, we have the JSROOT scripts directly inside Phoenix. I don't think that's a good idea.
With the `ScriptLoader` we have, it's possible to use an external source (CDN) to fetch the scripts we need and load them. Having a copy of the library inside the project will prove challenging for its future updates.

**Comment by spursbyte** [comment]
HI I WILL LIKE TO WORK ON THIS ISSUE. CAN YOU ASSIGN IT TO ME?

**Comment by 9inpachi** [comment]
Hi.
I don't think we need to assign it. Just give a try and open a pull request.
