### ISSUE TITLE
Extend usage guide and developer docs

### ISSUE THREAD

**Issue by 9inpachi** [HSF/phoenix#217]
Document usage of new features in the user guide.

* Adding labels
* Saving and loading state
* URL options etc.

Create developer guides for using and extending Phoenix API.

* Creating an event data loader
* Adding custom event data object type
* Working with Phoenix menu node
* Keeping track of loadable elements (`LoadingManager`)
* Three managers
* Phoenix and dat.GUI menu

**Comment by 9inpachi** [comment]
@EdwardMoyse, could you take a look at this and add any more topics we need to document? Especially for the developers side.

**Comment by EdwardMoyse** [comment]
Hi @9inpachi this looks great!

Maybe how to run VR mode? It probably won't be obvious to most that it requires running with SSL, which means you can't just do `yarn start`
