### ISSUE TITLE
Make it possible to switch perspective view off/on

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#22]
It can sometimes be useful to switch the perspective view off/on e.g. when you want to look down the barrel and see the layers.

**Comment by ss4774** [comment]
I am interested in tackling this issue and I have a few questions. I assume we want the ability to switch between normal (perspective) and orthographic camera view? Should the transition to orthographic view also align with one of the closest main axis (X, Y or Z) in a scene, or should the transition leave the original view direction unchanged?

**Comment by EdwardMoyse** [comment]
Hi Sebastien - that would be great if you could look into this! Yes, indeed what we want is to have an XY view, so the beamline would be coming out of the screen. For an example of what we mean, have a look at [this](http://atlas-vp1.web.cern.ch/atlas-vp1/home/gallery/a-higgs-4-muons-candidate-event-2/)

Top right you can see an orthographic view of the same event. In fact, it would be fantastic if we could (optionally) overlay the 2d view on the 3d but justr being able to switch between them would be a good start.

**Comment by ss4774** [comment]
Glad to be working on this project. I see, that kind of camera alignment really makes some clear and interesting views of an event. Currently I have added options to align a camera to any of the main axis and be able to switch between perspective or orthographic view at any point. I have made it such that when we align a camera with a certain axis, camera will align with that axis and move its orbit location with the alignment.
Do you think it would be better to recenter camera on the crossing plane and then align camera? This way we would always see the center of the scene in center of the canvas, regardless of camera's position, but we would always reset camera position when aligning.

I think a overlay of the 2D orthographic view would be quite possible at expense of some computing time on the GPU side. I think that would be a really nice addition to the event visualizer.
In my opinion we should however decide how to "limit" the information contribution of such overlay. Besides additional computing time the problem might arise from having too much objects cluttered together on the overlay and therefore make it unreadable.
Possible solution to this might be rendering only objects limited by an interval of front and back cutting planes. We can also try using transparent properties of these objects or adjust their color intensity property according to priory and make them more intuitive.

**Comment by EdwardMoyse** [comment]
We already have the possibility to move the camera to various 'fixed' views, which can be aligned with the beamline. So probably it would be enough simply to switch between perspective/orthographic and do the camera alignment separately?

**Comment by ss4774** [comment]
Yes, I think the perspective/orthographic switching works well with the fixed views. I have submitted a pull request so you can get a look at the result.

**Comment by emiliocortina** [comment]
@ss4774 Hi I've been trying out the new functionality and it works great. I decided to move the orthographic controls you added to the ui to a new folder called 'Views' together with the preset views we already had, hope you don't mind.
Thank you for your contribution!

**Comment by ss4774** [comment]
@emiliocortina Hello, no problem. Feel free to change and improve anything.
Glad to be of help.

**Comment by EdwardMoyse** [comment]
Done for a loooooong time.
