### ISSUE TITLE
Update three.js to latest version

### ISSUE THREAD

**Issue by 9inpachi** [HSF/phoenix#221]
I tried to update three.js to r125 with #210 but because of some major breaking changes I couldn't make it work at that time. As mentioned in the [CHANGELOG](https://github.com/mrdoob/three.js/releases/tag/r125), some of the things like the `Geometry` class have been removed from core.

Currently we are on r124 and the latest is r126 which also has some major breaking changes. Since the effort is not low and will require us to change our code logic quite a bit, I am putting this issue as a reminder. The sooner we do it the better.

**Comment by EdwardMoyse** [comment]
Ouch. The motivation for the Geometry migration is here:
https://discourse.threejs.org/t/three-geometry-will-be-removed-from-core-with-r125/22401

**Comment by 9inpachi** [comment]
The hard part is that this is NOT the only major breaking change. I noticed some other things as well mostly in the `cms-objects.ts` code I adapted from `ispy-webgl`.

**Comment by Ayushsunny** [comment]
> The hard part is that this is NOT the only major breaking change. I noticed some other things as well mostly in the `cms-objects.ts` code I adapted from `ispy-webgl`.

Is this issue still persist @9inpachi ?

**Comment by 9inpachi** [comment]
Yes. That's why it's open.

**Comment by Ayushsunny** [comment]
So, can I work on this?

**Comment by EdwardMoyse** [comment]
Sure - but just a warning that this might be a bit difficult. It will definitely teach you a lot about Phoenix though... ;-)

**Comment by Ayushsunny** [comment]
> Sure - but just a warning that this might be a bit difficult. It will definitely teach you a lot about Phoenix though... ;-)

I'm here to learn only @EdwardMoyse sir, so if it is difficult then why it is tagged as a "good first issue" ? or if you think as a new contributor i can solve this issue, please help me to do that .

**Comment by 9inpachi** [comment]
It's marked as a good first issue because there is a clear path to do it (the errors that come with updating three.js). You just have to solve those errors (of variable difficulties) compared to some issue that deals with the internal workings of Phoenix in detail.

**Comment by Ayushsunny** [comment]
> It's marked as a good first issue because there is a clear path to do it (the errors that come with updating three.js). You just have to solve those errors (of variable difficulties) compared to some issue that deals with the internal workings of Phoenix and requires an understanding of the architecture and coding conventions.
> 
> It should surely be doable with a bit of research. Just requires some old ways of defining geometries to be renewed after they were deprecated in r125.
> 
> And of course you can always contact us if you face any difficulty. ^_^

It would be glad to work under a nice mentor like you Fawad sir, and also I've started learning three.js for this

**Comment by ksraj123** [comment]
@9inpachi is this issue resolved?. If not, would like to give this a try.

**Comment by 9inpachi** [comment]
@ksraj123 This is resolved. You can look at other issues if you want to contribute. ^_^
