### ISSUE TITLE
Open compressed JiveXML

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#232]
We should add the ability to open compressed JiveXML (and probably just generally add this functionality, to support e.g. compressed json or any other text format).

I started prototyping it here:
https://github.com/EdwardMoyse/phoenix/tree/support-compressed-jivexml

It doesn't work - it fails with and error about the zip file being corrupted, so I've done something wrong.

I attached theexample compressed JiveXML I was using:
[test_events.zip](https://github.com/HSF/phoenix/files/6128034/test_events.zip)

**Comment by 9inpachi** [comment]
We already use this for CMS. JSZip is an easy to use library so it should
be simple.

**Comment by EdwardMoyse** [comment]
Yes, I was trying to copy what you did with cms, but add the ability to handle compressed JiveXML to the same function, so we didn't have to have lots of extra buttons in the dialog (e.g. Compressed JiveXML, Compressed JSON)
