### ISSUE TITLE
Construct a shareable link

### ISSUE THREAD

**Issue by 9inpachi** [HSF/phoenix#234]
This idea just popped up in my head.

So we can have some sort of simple UI - may be a popup window - where we can provide the user with a bunch of selectable or editable options like `hideWidgets`, `configUrl` etc. which will construct a shareable URL.

Here is a UI to illustrate the concept.

![url-constructor](https://user-images.githubusercontent.com/36920441/111363941-77f86400-86b2-11eb-8e6a-d42174b97de7.jpg)

I think it'd be pretty cool to have.

**Comment by EdwardMoyse** [comment]
That is a FANTASTIC idea!

**Comment by 9inpachi** [comment]
One more thing:

Apart from just the link, we can have another code snippet for including Phoenix in a blog or article like this:

```html
<iframe src=""https://phoenix-test.com/?hideWidgets=true"></iframe>
```
