### ISSUE TITLE
Per-track color ignored

### ISSUE THREAD

**Issue by cohm** [HSF/phoenix#237]
Hello!

It seems the color specified in the per-track dict is ignored, and all tracks are shown with the same color. See screen recording:

https://user-images.githubusercontent.com/7143813/111741834-6fa55200-8887-11eb-8752-7004bfcbe552.mov

The docs suggest the `"color"` entry in the dict should be picked up: https://github.com/HSF/phoenix/blob/master/guides/users.md#supported-object-types

Best,
Christian

**Comment by 9inpachi** [comment]
Hi!


Interesting find. This might be because of the dynamic config loaded where
color for each collection is defined, overriding the default Track color.

**Comment by 9inpachi** [comment]
Implementation notes: Use "null" instead of a fallback color in collection
color of Phoenix menu.

**Comment by 9inpachi** [comment]
Hey @cohm 

Are you loading the event data from the import/export options? Can you share the event data file so I can debug a little?

**Comment by 9inpachi** [comment]
@cohm -  Let me know if it works as expected at: http://phoenix-pr-238.surge.sh/

**Comment by cohm** [comment]
Thanks @9inpachi - that seems to do the trick:

<img width="1284" alt="Screenshot 2021-03-20 at 22 15 22" src="https://user-images.githubusercontent.com/7143813/111885734-e9455900-89c9-11eb-88a7-d29f7db4fb95.png">

In my input JSON the tracks are color coded based on charge, -1 is blue, neutral are green, and +1 are red. Here's the file I used too, in case it's interesting:

[HGTD_events6.json.zip](https://github.com/HSF/phoenix/files/6176426/HGTD_events6.json.zip)

Closing this - thanks for the quick fix!

**Comment by 9inpachi** [comment]
Great! Thanks for sharing the file!
