### ISSUE TITLE
Clipping settings does not reflect actual settings on "pre-set" event displays

### ISSUE THREAD

**Issue by ric-bianchi** [HSF/phoenix#246]
When opening the pre-set ATLAS example event display, the view is shown with clipped geometry; however, the "clipping setting" does not reflect the actual setting. See screenshot below:

<img width="1317" alt="Screen Shot 2021-03-31 at 15 21 53" src="https://user-images.githubusercontent.com/17335100/113151235-2bc22d80-9235-11eb-94f9-4e9ab9789568.png">

**Comment by 9inpachi** [comment]
Yeah, we kind of only have a one way binding of the UI with the event display.
