### ISSUE TITLE
Add 'start' clipping angle as well as opening angle

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#248]
So if we have a 45 degree cutaway, it should be possible to rotate the starting plane so the 45 degree cutaway moves through the detector. This could be done by adding a second slider, beneath the existing (see below). It will probably to make the second slider relative to the first, because opening angles >180 degrees caused strange behaviour in my tests.
<img width="216" alt="image" src="https://user-images.githubusercontent.com/6764617/113162185-5b763300-923f-11eb-86fc-42d4ebe3648c.png">

**Comment by spy-1234** [comment]
I would like to do a contribution on this issue, as I am in initial stages of open source development. So, please tell about how to proceed in the project.

**Comment by EdwardMoyse** [comment]
Hi @spy-1234 - firstly, welcome to the project! 

The first step is to get Phoenix running locally, so you can do development. Have you followed the instructions here:
https://github.com/HSF/phoenix#development
?

We also have a developer guide here:
https://github.com/HSF/phoenix/tree/master/guides/developers#readme

Once you have got it all working, we can discuss where you'd need to make changes for this (the first hint would be to look at where the existing slider is defined, and where it interacts with the rest of the code)

**Comment by Yash621** [comment]
Hello Sir @EdwardMoyse, can you guide me on this? I would like to work on this issue

**Comment by subho951m** [comment]
Sir, I could not set up environment for Phoenix. I installed node.js , then typed
`npm install --global yarn`
in node.js prompt, then I installed yarn but could not run it.
@EdwardMoyse sir, can you please help!

**Comment by EdwardMoyse** [comment]
Hi @subho951m - what error did you see?

**Comment by subho951m** [comment]
Sir an error was thrown multiple times that check network connection trying again...
I restarted my PC then also same thing happened. 
But luckily, suddenly it worked after few hours.

**Comment by subho951m** [comment]
@EdwardMoyse sir I want to know that whatever command we type in the git bash window of "Phoenix folder" or node js command prompt window, are they both same?
I mean both works right!
