### ISSUE TITLE
Change default save config name

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#262]
When saving state/configuration it would be better to save the run number / event number instead of `phoenix config.json` i.e. `runXXXXevtYYYY.json`

**Comment by 9inpachi** [comment]
Indeed, that's a good idea.

**Comment by 9inpachi** [comment]
I made it `runXXXX_evtXXXX.json` for better readability.

**Comment by EdwardMoyse** [comment]
Perfect.
