### ISSUE TITLE
Add LHCb loader to the LHCb demo app

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#281]
Currently it looks like:
![image](https://user-images.githubusercontent.com/6764617/115387872-866afb80-a1db-11eb-8a77-d2f6e8bebf0c.png)

**Comment by 9inpachi** [comment]
It seems we don't have import options for LHCb at all. The JSON here uses `PhoenixLoader`. Which again brings us to configurable import/export options. But this time, I have a lead which might be worth it (to specify the import options directly in `<app-ui-menu>` including the function and everything else.

I will give this a try once I am done with the other stuff.
