### ISSUE TITLE
Stop autorotate when dragging the detector/screen

### ISSUE THREAD

**Issue by SaMeHub** [HSF/phoenix#287]
Hi,

When in auto-rotate mode it would be good to stop auto-rotating once the user drags the detector/screen, rather than continuing to rotate against the user dragging ...

Cheers
Sascha

**Comment by 9inpachi** [comment]
This is already the case. If the user is dragging, the autorotate stops.

**Comment by 9inpachi** [comment]
Please reopen if I understood something incorrectly. :)
