### ISSUE TITLE
Phoenix menu displays only up to a certain character length

### ISSUE THREAD

**Issue by smitadarmora** [HSF/phoenix#316]
The Phoenix menu displays only up to a certain character length. Example image attached.
![phoenix_display](https://user-images.githubusercontent.com/85649044/121430611-eeb59e00-c93d-11eb-8386-e74896da02be.JPG)

**Comment by 9inpachi** [comment]
This is expected as we can't have long names taking up a lot of space. Hovering over the names does show the full title. And I added a `...` at the end for names that are too long to indicate that they aren't completely shown (to be merged though).
