### ISSUE TITLE
Make it possible to disable cuts or make it so if cuts are at bounds, then they don't count

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#339]
I worked out the problem with #336. It's very simple - the jets are failing the energy cut. Now, I could increase the maximum to something huge work around this, but I think a better solution would to have a checkbox to enable/disable cuts. 

Another option would be to make it so that if the cut == max, then it doesn't count - i.e. if lower cut == min, then there is no < cut, and it upper cut == max, then there is no > cut. But this would require changing the GUI to show the infinity symbol or something in these cases. So I think option 1 is cleaner.

<img width="1089" alt="Screenshot 2021-07-19 at 10 12 23" src="https://user-images.githubusercontent.com/6764617/126126717-5d42da6b-bc05-4790-a40e-2980b4ee3952.png">

**Comment by 9inpachi** [comment]
Interestingly, the "Random cuts" button works in a similar way.

**Comment by EdwardMoyse** [comment]
Fixed with #537
