### ISSUE TITLE
Number of jets in a collection

### ISSUE THREAD

**Issue by smitadarmora** [HSF/phoenix#347]
All the jets are not displayed in a jet collection.

Example: Jet collection: Antikt4TopoEMJets_AOD
No. of jets: 5
![number_of_jets](https://user-images.githubusercontent.com/85649044/128236160-e7eee756-1c0f-4308-b5d2-8c25812794c7.JPG)

No. of jets displayed: 3

**Comment by 9inpachi** [comment]
Hi @smitadarmora,

Can you try the "Collection > Cut Options > Reset cuts"? The Jets might be cut by default and we don't yet have a way to show that. See #272.
