### ISSUE TITLE
ATLAS geometry in Safari 15 is corrupted

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#358]
I'm pretty sure this is an issue with Safari, but it only seems to affect ATLAS geometry.

See screenshot:
<img width="1084" alt="Screenshot 2021-09-29 at 14 58 13" src="https://user-images.githubusercontent.com/6764617/135273202-605f1b10-9a9b-4fe9-a468-8652dbd43a95.png">

**Comment by 9inpachi** [comment]
Did you try toggling performance mode? Anti-aliasing might not be working
with Safari but that should affect other experiment too.

**Comment by EdwardMoyse** [comment]
No, that doesn't help. 

Performance is also TERRIBLE ... 3FPS, and I see the same performance degradation on Chrome too, though there the geometry is rendered okay. It actually make my entire laptop struggle. I tried a few other threejs demos and haven't managed to reproduce the performance degradation there yet, so it's not general.

I can't even open LHCb. :-(

On my iPhone, there are no issues.

I have a Radeon Pro 555 2 GB on my laptop.

I'll keep investigating ... I want to try to open the geometry in other gltf viewers to see if they also struggle with it.

**Comment by EdwardMoyse** [comment]
In this viewer in Chrome, I see the toroids fine, but performance is terrible:

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/6764617/135705778-4b241627-acb2-4804-bc2a-7a3cfbb72578.png">

In Safari, same file and same webpage:
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/6764617/135705808-edc4a078-2452-4840-aad8-2abbaa3ce7b9.png">

So it's NOT Phoenix-specific.

**Comment by EdwardMoyse** [comment]
This was tracked here: https://bugs.webkit.org/show_bug.cgi?id=232367

I believe it is now fixed. Closing.
