### ISSUE TITLE
question: track parameters

### ISSUE THREAD

**Issue by kratsg** [HSF/phoenix#36]
Looking at the [user docs](https://github.com/HSF/phoenix/blame/4ff6be51df838125fd54b778d95fc24b60c2f5e8/src/assets/docs/users.md#L58-L63)

> * 'Tracks' have the following information:
>   * 'chi2' - the chi2 of the fit, i.e. a number
>   * 'dof' - the degrees of freedom of the fit, i.e. a number (not necessarily an integer)
>   * 'params' - the parameters of the tracks, defined as d0,z0, ABC
>   * 'pos' - further positions along the track (a possible extension is to store positions and directions, to permit bezier curves, and perhaps a simple extrapolation system which would further reduce the amount of information needing to be stored)
>   * 'color' - (Optional) Hexadecimal string representing the color to draw the track.

It seems that the `params` are not used at all in the code (and seems to be called `dparams` in [src/assets/files/event_data/atlaseventdump2.json](https://github.com/HSF/phoenix/blob/master/src/assets/files/event_data/atlaseventdump2.json).

While `d0,z0` make sense, what is "ABC" here? Does that include q/p? Something else? It seems there are 5 parameters defined in some of the provided examples, but I can't find how it's actually used in the code such as this https://github.com/HSF/phoenix/blob/84da74cca49a7c7d047f74c5172cadb37a424679/src/app/services/loaders/phoenix-loader.ts#L70-L79

which calls

https://github.com/HSF/phoenix/blob/84da74cca49a7c7d047f74c5172cadb37a424679/src/app/services/loaders/objects/phoenix-objects.ts#L7-L63

**Comment by EdwardMoyse** [comment]
Hi Giordon, thanks for pointing this out - the documentation needs updating. The point of param/dparams is just to allow for experiment specific extensions. So here, for ATLAS the params would be d0,z0, phi, theta, q/p. It's not really used, but we might want to add e.g. some cuts based on these. They're effectively just labels. I'll clarify this.

**Comment by kratsg** [comment]
One would expect these to be used for drawing the track (apigee, perigee, etc...).

**Comment by EdwardMoyse** [comment]
Well, they are indirectly. The perigee parameters are just the first position:

https://gitlab.cern.ch/atlas/athena/blob/master/Event/DumpEventDataToJSON/src/DumpEventDataToJsonAlg.cxx#L113

**Comment by EdwardMoyse** [comment]
I think this is clearer now.
