### ISSUE TITLE
Add a checkbox to "Collections Info" to not show hidden objects

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#378]
Currently we highlight visible objects. It would be helpful to add a checkbox "Hide invisible objects" so we can easily find the objects we're interested in in the list.
![image](https://user-images.githubusercontent.com/6764617/143432660-3846b0bd-95c0-46b6-9bcc-6700b89f6270.png)

**Comment by gauravsharma21** [comment]
Hi @EdwardMoyse, Can I work on this issue?

**Comment by EdwardMoyse** [comment]
Sure! Thanks for looking into it.

**Comment by 9inpachi** [comment]
Closed with #380.
