### ISSUE TITLE
Scaling Jets to zero makes them vanish and then they cannot be recovered

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#379]
As above - I assume this is because once they have zero length, this cannot be recovered. If this is true, perhaps we can set a minimum length so we can always rescale them?

This is one of the reasons I want to try to think about a new way of drawing objects - i.e. when we change cuts / draw options we can completely redraw the collection. I'll open a separate ticket about this.

**Comment by 9inpachi** [comment]
> This is one of the reasons I want to try to think about a new way of drawing objects - i.e. when we change cuts / draw options we can completely redraw the collection.

Would be interesting to know what other reasons you have in mind. For just changing cuts and other draw options, redrawing the entire collection wouldn't be optimal. Since we are just changing how they look and not what they actually are.
