### ISSUE TITLE
Cuts are missing!

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#392]
I just tried to cut some tracks and jets, and the sliders are gone! Perhaps a side-effect of Angular13 @9inpachi ?
![Animation](https://user-images.githubusercontent.com/6764617/149305013-a9d12d01-1c3f-4c9e-bd57-1b9a18a0fd9f.gif)

**Comment by 9inpachi** [comment]
Didn't notice this. I will check.

**Comment by 9inpachi** [comment]
Seems that the library we are using angular-slider/ngx-slider#296 is not updated to support Angular 13. There's a fork with updates that we may be able to use: https://github.com/rp3e11/ngx-slider
