### ISSUE TITLE
Improve Event/Config selector with proper file browser

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#397]
This won't scale well as we add more data if we auto-expand the sub-directories:

![image](https://user-images.githubusercontent.com/6764617/150109076-3b6a8339-634a-46ed-a87c-4025ab62ff03.png)

**Comment by 9inpachi** [comment]
This should be in the PhoenixATLAS repo maybe? The component belongs there. We could move it here as well if need be.

I did have a try at this some months back but stopped working on it at some point. It would be some effort to create a generic file explorer like this that handles all edge cases.

**Comment by EdwardMoyse** [comment]
I think having a generic file browser is probably useful, but certainly the need is more pressing for ATLAS

**Comment by 9inpachi** [comment]
Solved with #402.
