### ISSUE TITLE
Add animation

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#4]
In VP1 we did this by defining e.g. a sphere that expanded with a timing tick, and only objects inside this radius were shown. This seems like a good place to start?

**Comment by ss4774** [comment]
Is it possible to somehow get or extract timestamps of a particular object detection inside sub-detectors? Combing this information with some kind of time scale and normalization mechanism we would be able to reconstruct quite accurate animation of a collision.

**Comment by EdwardMoyse** [comment]
Sorry @ss4774 - I never replied! In general no, we don't have precise timing information (at least not in the event data written out).

But @9inpachi did a nice implementation in #129
