### ISSUE TITLE
Update package versions

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#40]
We're getting vulnerability warnings etc now. Would be good to update packages to newer versions (I started, but realised it was going to be a bigger job than I expected).

**Comment by emiliocortina** [comment]
I have just added a commit to your new branch with a fix. At least they aren't showing on my computer anymore, if you can confirm we can merge the pull request.

**Comment by EdwardMoyse** [comment]
Ah great! Thanks!
