### ISSUE TITLE
Python checker script for the JSON event data files

### ISSUE THREAD

**Issue by andrewpap22** [HSF/phoenix#411]
Hello all, 

So as mentioned in our last meeting, I'll leave here the urls and information needed to somehow integrate the python checker inside Phoenix, either in this repository somehow, or in the Phoenix helpers repo and link it here throughout documentation. 

So, in the following 👉🏻 [link](https://gitlab.cern.ch/lhcb/Moore/-/merge_requests/1237/diffs#a0d380121093acdeadb9d9ab568044e9a24adb13_0_12) you can find the complete code for the checker which works properly right now based on the documentation right 👉🏻  [here](https://github.com/HSF/phoenix/blob/master/guides/users.md#using-phoenix-with-your-own-data). It also works properly for the LHCb JSON event data file that I will upload in my next pull request later on today and I will link it here once I do open it. 

The python checker can be easily modified to make it work within the CLI, we just need to write a few lines to provide a JSON file as input and then we'll have specific messages in case of errors or in case the file is structured as expected based on the Phoenix docs and thus one will know if his event data file can be properly visualised inside Phoenix. 

Hopefully this clears a bit what we discussed in our previous meeting! 

Cheers, 

Andreas

P.S. I'm pinging you here so you'll get the notification on this one! @EdwardMoyse @9inpachi @sponce

**Comment by sponce** [comment]
This issue should be assigned to me as I'm working on it. But for some reason (rights ?) I do not have a the assign button to do it myself.

**Comment by sponce** [comment]
One wonder I have is whether this is LHCb specific or should be provided as a generic type of detector in Phoenix. The current implementation is indeed LHCb specific in the sense that it uses dxdy and expects the fibers to belong to a plane of fixed z. But in general, should we not support a generic fiber detector in Phoenix ? I suppose the generic way would be to have both ends of each fiber stored into the json file. What do other people think ?

**Comment by sponce** [comment]
This is now tackled via https://github.com/HSF/phoenix-helpers/pull/3, which is completely experiment agnostic.
