### ISSUE TITLE
opacity not always working

### ISSUE THREAD

**Issue by sponce** [HSF/phoenix#421]
It looks like opacity is not working anymore for me when looking at the LHCb detector.
It works for TrackML for example, so it has to be related to the geometry itself.

Could one of you confirm/infirm this behavior ?
Just to the main site (http://phoenix-dev.surge.sh/#/lhcb) and try changing opacity on the Detector top level item.

**Comment by sponce** [comment]
@EdwardMoyse @9inpachi I fear I'll need help on this one. It seems I really need to change a number of things here. Let's me try to summarize and you tell me whether I'm on the right track :
  - all the code in the scene-manager relies on using names and passing them to getObjectByName if three
  - this is inherently creating the reported issue as the hierarchy is not taken into account
  - getObjectById should be used instead, but that means ids have ot be passed rather than names
  - this percolates to several interfaces, namely
    - the calls defined in scene-manager (objectVisibility, changeObjectColor, getObjectPosition, ... many others)
    - several methods of phoenix-ui and muni-ui, e.g. addGeometry, addEventDataFolder, ...
    - methods of the event-display, e.g. load/parse*Geometry
And of course I did not cover the whole tree.

Do you see a way out without changing all these interfaces ?

**Comment by 9inpachi** [comment]
I think I partly get what you mean. I am giving it a try. Hopefully, it isn't that complex.

**Comment by 9inpachi** [comment]
So it's not about being unable to get the object. We have the object but the opacity isn't being applied to the material of objects. I am not sure why.

**Comment by sponce** [comment]
Could it be related to some warnings that I get when exporting to gltf ?
```
GLTFExporter: Use MeshStandardMaterial or MeshBasicMaterial for best results.
```
The corresponding code is : 
```javascript
if ( material.isMeshStandardMaterial !== true && material.isMeshBasicMaterial !== true ) {
   console.warn( 'GLTFExporter: Use MeshStandardMaterial or MeshBasicMaterial for best results.' );
} // pbrMetallicRoughness.baseColorFactor
```

**Comment by sponce** [comment]
Thanks a lot ! Note that I realize we are discussing a different issue than the one of this issue here. This one concerns name clashes. Maybe we just change the title and put 2 in one

**Comment by 9inpachi** [comment]
Ah okay, I didn't realize that. :D

Yeah, feel free to change the title or create a new one. Fine by me either way.

**Comment by sponce** [comment]
ok, I've updated this MR to dedicate it to the opacity issue and create #426 for the menu issues

**Comment by EdwardMoyse** [comment]
I believe this is fixed (reopen if not).
