### ISSUE TITLE
Clipping planes are not modifiable

### ISSUE THREAD

**Issue by sponce** [HSF/phoenix#427]
After wondering why the LHCb Muon would not allow to be clipped while the rest of the detector was fine with it, I found this piece of code : 
```javascript
this.clipPlanes = [
      new Plane(new Vector3(0, 1, 0), 0),
      new Plane(new Vector3(0, -1, 0), 0),
      new Plane(new Vector3(0, 0, 1), -15000),
    ];
```
at https://github.com/HSF/phoenix/blob/master/packages/phoenix-event-display/src/managers/three-manager/index.ts#L93

And we do not seem to have a way to change these hardcoded values. In particular the -15000 is not enough in my case !

**Comment by DamianArado** [comment]
> And we do not seem to have a way to change these hardcoded values

Can you try using [.set](https://threejs.org/docs/#api/en/math/Plane.set) for clipping planes?

**Comment by sponce** [comment]
Sorry, I'm not an expert in javascript, so I may be saying something stupid here, but does the declaration
```javascript
 private clipPlanes: Plane[];
```
not mean that I can not call set (or any other method) on clipPlanes ?

**Comment by 9inpachi** [comment]
We don't expose the clipping planes to the consumer. There are multiple ways of doing this. Let me know if you have any preference.

1. Get the clipping planes array and modify the planes manually (`ThreeManager.getClippingPlanes()`)
2. Specify the clipping planes in the configuration we pass to the event display (`EventDisplay.init(configuration)`)
    Here you can have any number of clipping planes. We can make the property optional and fallback to some default value.
4.  Both.

**Comment by DamianArado** [comment]
> I can not call set (or any other method) on clipPlanes ?

Indeed. We can add a method in [three-manager](https://github.com/HSF/phoenix/blob/master/packages/phoenix-event-display/src/managers/three-manager/index.ts) to modify the clipping planes using `.set` if that can satisfy your use-case.

**Comment by 9inpachi** [comment]
> Indeed. We can add a method in [three-manager](https://github.com/HSF/phoenix/blob/master/packages/phoenix-event-display/src/managers/three-manager/index.ts) to modify the clipping planes using .set if that can satisfy your use-case.

Just a setter may not work. The planes are linked to the detector 3D objects by reference. Changing the value is going to apply them for geometries we may add later on but not the ones that are already added. We will have to modify the existing clipping planes in the array to have any effect.

**Comment by sponce** [comment]
I think I would vote for option 2 (setting planes in the config) but I do not have a strong opinion
