### ISSUE TITLE
Objects inside transparent outer object disappear

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#430]
If I turn off clipping, you can see that the Pixels disappear.

![Animation](https://user-images.githubusercontent.com/6764617/166412963-ecfabbe1-b8e2-4e99-94f1-2a4a031ff70b.gif)

**Comment by 9inpachi** [comment]
Which "Pixels" do you mean? The event data or the detector geometry?

**Comment by EdwardMoyse** [comment]
I mean the detector geometry - the purple donut (with a bite taken out of it) in the middle of the screen. It's only visible when clipping is on.

**Comment by EdwardMoyse** [comment]
I mean the detector geometry - the purple donut (with a bite taken out of it) in the middle of the screen. It's only visible when clipping is on.

**Comment by EdwardMoyse** [comment]
Won't fix.
