### ISSUE TITLE
Having a button to rotate on events

### ISSUE THREAD

**Issue by sponce** [HSF/phoenix#447]
It would be nice that one can activate a mode where events are automatically rotated every x seconds.

**Comment by EdwardMoyse** [comment]
I thought I'd already replied to this! Does the autorotate button not do what you want?
https://github.com/HSF/phoenix/blob/master/guides/users.md#the-phoenix-iconbar

**Comment by sponce** [comment]
Sorry I was not clear here. I meant that we "rotate" on a list of events. That is you show a given event for say 10s and switch to the next event for the next 10s and so on. Completely independently of a geometrical rotation around the origin !
