### ISSUE TITLE
Closed geometry cannot be reopened!

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#463]
![Jun-27-2022 11-31-32](https://user-images.githubusercontent.com/6764617/175908653-839c666b-0a09-49d1-b042-a3cbb70aad17.gif)

See the gif - this is a serious bug!

**Comment by 9inpachi** [comment]
Can you try opening the node and check nodes inside are toggled on? We save the state of the child nodes, it might be related to that.

But overall, everything looks fine to me on: https://hepsoftwarefoundation.org/phoenix/#/atlas
