### ISSUE TITLE
tool bar not hidden in screenshot mode

### ISSUE THREAD

**Issue by sponce** [HSF/phoenix#464]
I believe this was working fine in the past, but somehow is broken today. The tool bar stays on the screen in screenshot mode, and trying to hide it makes the screenshot mode vanish. annoying

**Comment by 9inpachi** [comment]
It seems to be working fine.

![image](https://user-images.githubusercontent.com/36920441/176255189-16e17d52-595f-4a54-b606-4920f9994ff5.png)
