### ISSUE TITLE
API docs are not up to date

### ISSUE THREAD

**Issue by sponce** [HSF/phoenix#472]
E.g. the PresetView class does not include the clipping yet. I suppose this should be automatically updated with each merge of a PR

**Comment by 9inpachi** [comment]
The API docs are for each release. The ones you see right now are for
Phoenix v2.9.0. Since Phoenix is supposed to be used as an external
package, the API docs aren't updated with each merge to master but only on
release so people don't see what's not released yet.

**Comment by 9inpachi** [comment]
@sponce Can we close this or do you have any other approach in mind?
