### ISSUE TITLE
Enhancement: Allow customization of link URL for {{ expriment }} logo

### ISSUE THREAD

**Issue by wdconinc** [HSF/phoenix#479]
Right now the UI encodes the logo link as (in `packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/experiment-info/experiment-info.component.html`):
```
  <a
    class="experimentLogoWrapper"
    target="_blank"
    rel="noopener noreferrer"
    *ngIf="experiment"
    href="https://home.cern/science/experiments/{{ experiment }}"
  >
    <img
      class="experimentLogo"
      src="assets/images/{{ experiment }}.svg"
      alt=""
    />
  </a>
```
which doesn't allow for links to experiments outside of CERN.

**Comment by 9inpachi** [comment]
Good point. We can make these configurable by passing the options as attributes/inputs to the component.
