### ISSUE TITLE
Change the load event data icon

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#50]
Currently it's a printer, which is pretty confusing. 

Better would be:
https://github.com/HSF/phoenix/blob/master/src/assets/icons/upload.svg

However when I tried to change this in atlas.component.html, all I got was a blank icon, so I obviously missed a step.

**Comment by 9inpachi** [comment]
Hi Edward,
Hope you are well.

I added the icon but would like to know if it seems consistent to you. The file icon Emilio uses was made specifically for the options panel so its borders are thin as compared to the upload icon.

![image](https://user-images.githubusercontent.com/36920441/75067824-b9e6c300-550f-11ea-8556-b36971052412.png)

**Comment by EdwardMoyse** [comment]
I think that looks great!

**Comment by 9inpachi** [comment]
Great!

I'll send a PR then.
