### ISSUE TITLE
Outline pass not working in selection mode

### ISSUE THREAD

**Issue by 9inpachi** [HSF/phoenix#508]
It seems there is an error in some shader. To reproduce, select "Object selection" from the icon bar and try hovering over any object.

![phoenix-selection-error](https://user-images.githubusercontent.com/36920441/198105444-2c079bec-32c1-4606-a29f-b45f273e90fa.PNG)

**Comment by Somya-Bansal159** [comment]
I tried reproducing the issue, but it is working fine on my side as in the image below.

![image](https://user-images.githubusercontent.com/77807055/223022266-f3c5a90e-5e32-40b8-aa4b-f38fdc33ab86.png)

Does the error still persist?

**Comment by 9inpachi** [comment]
I cannot reproduce either.
