### ISSUE TITLE
Opacity no longer works for the calo cells

### ISSUE THREAD

**Issue by kjvbrt** [HSF/phoenix#517]
![image](https://user-images.githubusercontent.com/34742917/202206094-1c850226-504f-4068-8640-edd420168e47.png)

**Comment by 9inpachi** [comment]
It seems opacity isn't working for any of the event data.

**Comment by 9inpachi** [comment]
For jets, it seems to work. The source code is here if you want to take a look: https://github.com/HSF/phoenix/blob/448eb4fafc722f2c6c1febad69c7a5ce047a963e/packages/phoenix-event-display/src/managers/ui-manager/phoenix-menu/phoenix-menu-ui.ts#L251
