### ISSUE TITLE
In embedded view, 'open full' link should open the same event

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#527]
See for example:
https://atlas.cern/updates/briefing/search-heavy-W-bosons

when we click 'open full' it opens the default event, which is not what we want. It should be the same URL as the embedded event.

**Comment by EdwardMoyse** [comment]
I actually do not understand why this does not work correctly - if I look at 
```typescript
export class ExperimentLinkComponent implements OnInit {
  private experimentLink: string;

  ngOnInit() {
    this.experimentLink = window.location.href.split('?')[0];
  }

  goToExperiment() {
    window.open(this.experimentLink, '_blank');
  }
}
``` 
It seems like experiment link should be working correctly...

**Comment by EdwardMoyse** [comment]
Ah no! It just gets the link to e.g. phoenixatlas but drops everything else. I think I can make a patch, but I'm not quite sure how to test this.

**Comment by 9inpachi** [comment]
You can use this URL:
https://phoenixatlas.web.cern.ch/PhoenixATLAS/?geom=simple&embed=true&file=data/event_data/HWW/VBF/JiveXML_VBF_1_337705_1829797121.xml&type=jivexml
It will have the show full experiment button.

And you just need to remove the "embed" query parameter.

```ts
const url = new URL(window.location);
url.searchParams.delete('embed');
this.experimentLink = url.toString();
```

Best,
Fawad
