### ISSUE TITLE
Possible typo in make-picture.component.test.ts

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#544]
https://github.com/HSF/phoenix/blob/e5e2e7c589b300854772b18aac0556fab007c254/packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/make-picture/make-picture.component.test.ts#L15

Hi @sponce,

Shouldn't this line be: 
```typescript
fixture = TestBed.createComponent(MakePictureComponent);
```
? 

I'm really not sure why this doesn't fail in the main CI, but it does fail locally for me on MacOS.

**Comment by EdwardMoyse** [comment]
Update: not just spotted locally by me:
https://github.com/HSF/phoenix/actions/runs/3985370337/jobs/6832668405

**Comment by sponce** [comment]
Of course it should ! How could this have passed test locally and then in the ci ?
There is something fishy here. It's like for the uuid failure on https://github.com/HSF/phoenix/pull/536...

I've tried to make a fix, but you seem to have removed make-picture for the moment so I cannot
