### ISSUE TITLE
ATLAS calo cells are no longer rendered in the correct place

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#552]
See the screenshot below. They should be on a cylinder, but are on a sphere.
<img width="678" alt="image" src="https://user-images.githubusercontent.com/6764617/215057342-9bb1c37b-a79b-4ff1-9b51-25fa37aef22a.png">

I assume this was caused by #519 (my fault for not checking carefully!)

**Comment by Afteeruym1** [comment]
can i work on it?

**Comment by EdwardMoyse** [comment]
Sure - if you want an example of it working, have a look at the yellow cubes (Calo clusters) here:
https://phoenixatlas.web.cern.ch/PhoenixATLAS/

**Comment by EdwardMoyse** [comment]
@Afteeruym1 I think I found the fix for this (sorry for not consulting you first, but this is urgent to fix for ATLAS)
