### ISSUE TITLE
momentum cuts don't seem to work 

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#56]
Trying on ATLAS, and the tracks aren't changing. Other cuts work.

**Comment by 9inpachi** [comment]
It seems that the momentum for each track isn't specified in the event file ((assets/files/event_data/atlaseventdump2.json)[https://github.com/HSF/phoenix/blob/master/src/assets/files/event_data/atlaseventdump2.json]).
Have you tried loading with JiveXML?

**Comment by 9inpachi** [comment]
Just found. Looks like the word "momentum" is being used to get the momentum for tracks (`track.momentum`). Since event data uses `mom` to address the momentum of tracks, changing this to `mom` seems to fix the issue.
