### ISSUE TITLE
Make overlay more functional

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#57]
I'm thinking that it would be good to be able to resize it and switch it from orthographic/perspective independently. Maybe on mouse over, some controls could appear - a pin to fix it, and cube/perspective cube for ortho/persp?

**Comment by 9inpachi** [comment]
Ed, by
> a pin to fix it

Do you mean to fix the overlay view so it doesn't move or zoom with the main view controls?

**Comment by 9inpachi** [comment]
Fixed in #81 and 30e568fdec28511491f28e73c7737e4af189e407.
