### ISSUE TITLE
Loading configuration is buggy

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#570]
I've noticed this several times - we've had reports of users seeing the ATLAS toroid magnets on some browsers but not on others (and checking the configuration they are disabled).

Here is another example: if you open [this](https://phoenixatlas.web.cern.ch/PhoenixATLAS/?file=data%2FBriefings%2FJiveXML_304008_1533145462.xml&type=jivexml&config=data%2FBriefings%2Frun304008_evt1533145462.json) link, you will see ALL the jet collections, despite only one being enabled in the configuration. It's like the menu and the scenegraph are out of sync.

![Animation5](https://user-images.githubusercontent.com/6764617/228176323-e1ffb182-eb33-4bec-8f6d-79f1704217c4.gif)

**Comment by EdwardMoyse** [comment]
I looked into this more, and I *think* it must be a problem with async calls in some manner I really don't understand, but it seems to be in `loadFile` from https://github.com/HSF/phoenix/blob/main/packages/phoenix-event-display/src/helpers/file.ts

My debugging:
I put a `console.log()` in `state-manager.ts loadStateFromJSON`

When I open phoenix and try to manually load a configuration file, I *do not* see this output i.e. the configuration file is not loaded (this explains the weird problems that I and others have been having).

If, however, I set a breakpoint at line 30 of `file.ts`, then I DO see this output. So it seems like forcing the code to stop there allows something else to happen in time?

Digging a bit deeper it seems like the `input.onChange`
https://github.com/HSF/phoenix/blob/ef5a97498d3269e7a99cb4e7d51d92e18131ec62/packages/phoenix-event-display/src/helpers/file.ts#L34

If I change the code to 
```typescript
  inputFile.click();
  setTimeout(() => {
    console.log('Let us just wait a second');
}, 1000);
};
``` 
then it works as expected (but obviously this is a hack and not a fix).

I only see this problem on Safari.

Pinging @9inpachi and @DamianArado, who will certainly have a better idea what could be causing this than I do!

**Comment by 9inpachi** [comment]
To me, this looks like it might be because the parent menu item is toggled on? It may be that the parent menu item's state is being applied after the children. But loading of the state is synchronous. Although, since we iterate over three.js objects asynchronously, that might be what's causing the issue. Not sure at all.

**Comment by EdwardMoyse** [comment]
Hi @9inpachi - possibly, but the second example I found definitely isn't. Since it is probably(?) a different bug, I opened !582

**Comment by EdwardMoyse** [comment]
Fixed.
