### ISSUE TITLE
Running linters against staged git files

### ISSUE THREAD

**Issue by DamianArado** [HSF/phoenix#578]
There exist tools like [lint-staged](https://github.com/okonet/lint-staged) which we can use to make sure we are not committing the usually unwanted linting error on the CI. 

It will make sure that we’re focusing on the actual problem if we see a failed CI output and it will also reduce the number of irrelevant git commits.

**Comment by EdwardMoyse** [comment]
That looks very interesting, thanks! I assume this is more something we add to the documentation though, as advice to developers? i.e. it's not something we can do centrally?

**Comment by DamianArado** [comment]
I'll add this centrally in the config, so that on each commit this gets implemented plus in docs, this gets added under linting so that devs know what's happening and why.

**Comment by 9inpachi** [comment]
In my experience, the setup with husky and lint-staged becomes stale in some time and stops working for a lot of people. I haven't looked into it to know why. But we can certainly try to set it up in Phoenix.

**Comment by DamianArado** [comment]
Yes, it needs to work consistently. Otherwise, we won't get any benefit out of it.
