### ISSUE TITLE
Not able to set up the Angular App

### ISSUE THREAD

**Issue by davzuliani** [HSF/phoenix#619]
Dear experts,
I'm trying to set up an Angular app following the instructions. Up to creating the Angular app, everything is fine.
But when I try to set up `phoenix-ui-components` and try to do `ng serve --open`, I get the following error:

`./node_modules/phoenix-ui-components/node_modules/@angular/forms/fesm2020/forms.mjs:6869:26-42 - Error: export 'ɵcoerceToBoolean' (imported as 'ɵcoerceToBoolean') was not found in '@angular/core' `

Is there a way to solve this issue?

I'm working on pop_os 22.04.

Thank you very much

**Comment by 9inpachi** [comment]
Hi, can you check which version of Angular you are using?

```sh
ng --version
```

**Comment by davzuliani** [comment]
Sure, this is the output

`

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.1
Node: 18.17.1
Package Manager: npm 9.6.7
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1602.1 (cli-only)
@angular-devkit/core         16.2.1 (cli-only)
@angular-devkit/schematics   16.2.1 (cli-only)
@schematics/angular          16.2.1 (cli-only)
`

**Comment by 9inpachi** [comment]
Try to use Angular v15. It works for me.

**Comment by DraTeots** [comment]
Same for angular 17, while I see that phoenix-ng-components now on 16.1.8. Are there plans to move to 17? Before the next release or after?

**Comment by EdwardMoyse** [comment]
No plans at the moment, but I can investigate to see how much work it will be.

**Comment by EdwardMoyse** [comment]
Updated to Angular 17 in on main.

**Comment by EdwardMoyse** [comment]
This should be fixed now, but please let us know if not and we can re-open.

**Comment by DraTeots** [comment]
I wanted to make a PR to update the documentation. In particular [guides/developers/set-up-phoenix.md](https://github.com/HSF/phoenix/blob/main/guides/developers/set-up-phoenix.md) to correspond to Angular 17 created application. But I wanted to ask, Angular now uses "standalone" controls by default, using this template has many more differences than the original tutorial. The flag  `--standalone=false` could be used to create a template close to the tutorial but still needs changes here and there. I ended up with the default standalone constrols application. Everything works. So would you give me the green light on such PR and should we use the default angular 17 project or `--standalone=false` ?
