### ISSUE TITLE
[feature] Support of DD4hep geometry input

### ISSUE THREAD

**Issue by bartosik-hep** [HSF/phoenix#639]
From the code it doesn't seem like geometry input in `DD4hep` format is supported. Is it something being worked on or considered for the near future? 

Many future experiments are using it to describe their geometries and the present ones are also migrating to [`DD4hep`](https://dd4hep.web.cern.ch/dd4hep/page/showcases/), so it would have been great for the experiment-agnostic event visualization tool to support it.

**Comment by EdwardMoyse** [comment]
Hi, I'm going from memory here, so take this with a pinch of salt, but my understanding of supporting DD4HEP was that this wasn't really feasible, since DD4HEP in use in a real detector is typically going to be a mixture of xml and C++ i.e. you cannot just open an XML file, you need the code in order to parse it.

That said, we do have instructions about how to turn ROOT TGeo into something Phoenix understands:
https://github.com/HSF/phoenix/blob/main/guides/developers/convert-gdml-to-gltf.md#concert-root-to-gltf

**Comment by EdwardMoyse** [comment]
Kind of - I think it's probably a bit rudimentary. 

But for example, I went to the Playground (https://hepsoftwarefoundation.org/phoenix/#/playground) and tried to import the root geometry [shipped ](https://github.com/HSF/phoenix/blob/main/packages/phoenix-event-display/src/tests/files/geometries/rootgeom.root)with Phoenix, and when the popup appeared asking for "Enter object name in ROOT file", I typed "simple1"

This gives the following:
![image](https://github.com/HSF/phoenix/assets/6764617/c6046e19-b926-4b81-9773-74dc439e137e)

So *something* works, but I don't know if anyone uses this in "production"

**Comment by EdwardMoyse** [comment]
Very nice!

**Comment by DraTeots** [comment]
I need to say, that converting to gltf and working with gltf provides much nicer experience and results. Especially using Blender for GLTF and other tools. But I don't think it is a problem of Phoenix but rather how how one sets up a pipeline to convert from dd4hep to geometry and import to phoenix. Currently just working with format designed for 3d and WebGL and tools designed for working with 3D just work better than root geometry format. I will write the full steps and ways to work with DD4HEP data in the end of my experiments

<img width="1579" alt="image" src="https://github.com/HSF/phoenix/assets/4732545/f03cbdec-b61f-46f1-a45f-e1f3cbbce84c">

**Comment by DraTeots** [comment]
DD4Hep plugin with custom stepping action exporting track steps to phoenix format. 
<img width="1069" alt="image" src="https://github.com/HSF/phoenix/assets/4732545/b06a8b7e-1ac4-4a84-b511-e0edc227da1d">

And here are optical photons
<img width="949" alt="2024-03-26 02_17_31-Firebird - Vivaldi" src="https://github.com/HSF/phoenix/assets/4732545/48e905d3-dd49-4479-9c27-88d05aa29739">

It is fun!

**Comment by bartosik-hep** [comment]
@DraTeots this is really interesting... Is this plugin available as part of some public repository to see the code? It would be very useful.

**Comment by DraTeots** [comment]
Yes, I am making them public. Give me a day or two as I have to separate my pile of experiments to more sane projects and communicate with EIC software and computing where to better put them (presumably github.com/eic). I'll let you know here as it is alive.

**Comment by DraTeots** [comment]
Sorry for a long absence. Unfortunately didn't have time to finish everything before the APS and vacation. Now I am back and will update on this soon.

**Comment by EdwardMoyse** [comment]
Just a quick ping to ask on progress on this?

**Comment by EdwardMoyse** [comment]
I think this isn't really a Phoenix issue now, given the conversation moved to a DD4HEP plugin. So closing.
