### ISSUE TITLE
Can't resolve 'phoenix-ui-components'

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#652]
I just tried updating PhoenixATLAS to phoenix 2.15.1... but I think I have messed something badly up now!

```
Build at: 2024-03-22T11:40:19.808Z - Hash: 2112880c630e3e3e - Time: 384ms

./src/app/app.module.ts:6:0-56 - Error: Module not found: Error: Can't resolve 'phoenix-ui-components' in '/Users/emoyse/LocalDocuments/PhoenixATLAS/src/app'

./src/app/pages/atlas/atlas.component.ts:8:0-44 - Error: Module not found: Error: Can't resolve 'phoenix-ui-components' in '/Users/emoyse/LocalDocuments/PhoenixATLAS/src/app/pages/atlas'
```

Probably I did something wrong with building the library in `angular.json`

cc @9inpachi

**Comment by 9inpachi** [comment]
Hey Ed, have you checked the list on https://update.angular.io/?l=3&v=16.0-17.0 for updating Angular?

This [change](https://github.com/HSF/phoenix/commit/bbf29872a079d93a9ce1ea472a5380abf8188d51#diff-d88bb0349404e355d473f08a8e35152da2879fa3e8ba27a5ef3338fc46214025L138) might be causing the `phoenix-ui-components` to not build.

Apart from that, any reason you [changed the `allowSyntethicDefaultImports`](https://github.com/HSF/phoenix/commit/bbf29872a079d93a9ce1ea472a5380abf8188d51#diff-9abc61a2b20285673dd39dcb2794c7a47cc4eeb34e23906d356dd392eb2a5839L12)? This option is important for importing default modules, otherwise you have to use `import * as LIB from 'lib'`.

**Comment by 9inpachi** [comment]
I have checked and there is something wrong with the latest update of phoenix libraries. I don't have the capacity to check exactly but I think you need to correctly update angular using:

```sh
yarn ng update @angular/animations@17 @angular/cdk@17 @angular/common@17 @angular/compiler@17 @angular/core@17 @angular/forms@17 @angular/material@17 @angular/platform-browser@17 @angular/platform-browser-dynamic@17 @angular/router@17 @angular-devkit/build-angular@17 @angular/cli@17 @angular/compiler-cli@17

yarn ng update @angular/animations@16 @angular/cdk@16 @angular/common@16 @angular/compiler@16 @angular/core@16 @angular/forms@16 @angular/material@16 @angular/platform-browser@16 @angular/platform-browser-dynamic@16 @angular/router@16 @angular-devkit/build-angular@16 @angular/cli@16 @angular/compiler-cli@16
```

**Comment by EdwardMoyse** [comment]
Hi @9inpachi 

Thanks for looking! I did follow https://update.angular.io/?l=3&v=16.0-17.0  and I did do: `ng update @angular/core@17 @angular/cli@17` etc

In fact it was this that changed `allowSyntethicDefaultImports`. I will try reverting this, and also the ""builder": change (though something here DOES need to be changed, or we get:
```
Error: Could not find the '@angular-devkit/ng-packagr:build' builder's node package.
```

**Comment by DraTeots** [comment]
I guess, I saw this error when tried to make a new application using angular 17. In the end I went to `node_modules/phoenix-ui-components/package.json` and saw them

```json
"module": "dist/fesm2015/phoenix-ui-components.mjs",
  "es2020": "dist/fesm2020/phoenix-ui-components.mjs",
  "esm2020": "dist/esm2020/phoenix-ui-components.mjs",
  "fesm2020": "dist/fesm2020/phoenix-ui-components.mjs",
  "fesm2015": "dist/fesm2015/phoenix-ui-components.mjs",
  "typings": "dist/index.d.ts",
  "sideEffects": false,
  "gitHead": "cbefd755a9b18bf775bdc4cbdecba12f7281b9d4"
  ```
  
  while in reality dist had only `fesm2022` and `esm2022`. I fixed it like this 

```json
  "module": "dist/fesm2022/phoenix-ui-components.mjs",
  "esm2022": "dist/esm2022/phoenix-ui-components.mjs",
  "fesm2022": "dist/fesm2022/phoenix-ui-components.mjs",
  "typings": "dist/index.d.ts",
  "sideEffects": false,
  "gitHead": "cbefd755a9b18bf775bdc4cbdecba12f7281b9d4"
```  

With that I got phoenix GUI mostly running but failing in the end on of stats.js `require(...)` (that thing that shows threejs framerate in the corner)

Hope this can somehow help

**Comment by 9inpachi** [comment]
Okay, that is it then. We just need to change the package.json for the UI
lib. We replace the one generated by the Angular CLI with a custom one
because the directory structure of our library is different.

**Comment by 9inpachi** [comment]
This has been fixed. The [release action was successful](https://github.com/HSF/phoenix/actions/runs/8411051437/job/23030192496) and v2.16.0 of phoenix is now available on npm.

@EdwardMoyse I have also updated PhoenixATLAS and it's working fine.

As I previously suggested, please update the dependencies more frequently to avoid these kind of issues.

**Comment by EdwardMoyse** [comment]
Amazing! Thank you so much @9inpachi!
