### ISSUE TITLE
Screenshot icon is missing

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#654]
![image](https://github.com/HSF/phoenix/assets/6764617/a6ad890e-c7e0-4ede-a371-7b48afda14b2)

Weirdly, I don't think this happens when running Phoenix locally ... it seems to only happened when Phoenix is deployed.

Tentatively assigning to Sebastien, but I will take a look as well tomorrow.

**Comment by sponce** [comment]
Thing is I do not know how to reproduce. The LHCb deployment on the web (https://lhcb-eventdisplay.web.cern.ch/) does not seem to have the problem. I've also checked the diff with head of master and nothing seems related to this icon.

Can you tell me how to reproduce ? Which browser, which platform, which webpage ?

**Comment by EdwardMoyse** [comment]
Hi @sponce - sorry, indeed I was not very clear. One way to reproduce is to install [PhoenixATLAS](https://github.com/ATLAS-experiment/PhoenixATLAS) i.e.
```
git clone https://github.com/ATLAS-experiment/PhoenixATLAS.git
cd PhoenixATLAS
yarn install
yarn start
```

But actually I noticed something which is probably relevant. 

In [our instructions](https://github.com/HSF/phoenix/blob/main/guides/developers/set-up-phoenix.md#set-up-assets) we say:

> And lastly, download [these assets](https://github.com/HSF/phoenix/tree/main/packages/phoenix-ng/projects/phoenix-ui-components/lib/assets) (icons and images used by the Phoenix UI components) and put them in the src/assets directory of your app.

If I look in that directory I see e.g. `ss-mode` (as used in [ss-mode.component.html](https://github.com/HSF/phoenix/blob/main/packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/ss-mode/ss-mode.component.html)), but no `png.svg`. I can't actually find it anywhere in the repo, so I'm not quite sure where it comes from?

**Comment by 9inpachi** [comment]
The library doesn't use the files and they are served by the app through an endpoint. They exist in the library as well since they need to be copied over to any application that will use the library.

**Comment by EdwardMoyse** [comment]
Okay, we we should copy `png.svg` to `/packages/phoenix-ng/projects/phoenix-ui-components/lib/assets/icons`?

And I need to copy it as well to `PhoenixATLAS`?

**Comment by sponce** [comment]
I'm a bit lost in the structure of all the code, but the file is in `packages/phoenix-ng/projects/phoenix-app/src/assets/icons/png.svg` and it seems to be sufficient for LHCb to find it. Now it is true that if I check other icons (e.g. clipping.svg) it seems to be duplicated into `packages/phoenix-ng/projects/phoenix-ui-components/lib/assets/icons`. I'm not sure why everything should be duplicated. Does not look super optimized I must say
