### ISSUE TITLE
Instructions for adding a new experiment are not (no longer?) working

### ISSUE THREAD

**Issue by tmadlener** [HSF/phoenix#667]
I was trying to follow [these instructions](https://github.com/HSF/phoenix/blob/830c19019038345fb5b529754dde8fb0bc6c60a1/guides/developers/set-up-phoenix.md) to try and setup an event display for a new experiment. Are these still expected to work? I am mainly asking because I ran into a few issues in a few of my attempts. Any inputs / help would be greatly appreciated.

Main reasons for this issue:
- The instructions still use `npm`, but phoenix itself seems to have switched to `yarn`
- The default angular version one gets nowadays via `npm install -g @angular/cli` is 18. However, since angular >= 17 [defaults seem to have changed](https://github.com/HSF/phoenix/blob/830c19019038345fb5b529754dde8fb0bc6c60a1/packages/phoenix-ng/package.json#L50) and it's necessary to do a `ng new my-app --no-standalone --routing true --style scss` (do I want the server side rendering here?)
- Even if I explicitly use angular 16 I run into build issues.

Maybe I am just missing the correct combination of node and angular versions? I am trying this on Ubuntu 22.04 using the following as a base
```console
$ node --version
v20.15.1
$ npm --version
10.7.0
```
I have also tried with node 18, but without success.

If the instructions are still supposed to work, I can also provide more detailed information about the issues I have run into.

**Comment by DraTeots** [comment]
```
ng new my-app --no-standalone --routing true --style scss
```

1. It should work with angular 17 as Phoenix uses angular 17
2. With tutorial finished,  `ng serve` same as `npm run start`  will work, but `ng build` has much more deep issues and I was not able to make it work without severe builder reconfigure. Don't fall into this trap.

**Comment by DraTeots** [comment]
@EdwardMoyse If you would like, I can rewrite this tutorial to use standalone controls and simplify it for newcomers.

**Comment by EdwardMoyse** [comment]
That would be fantastic! Please feel free to rewrite it.

**Comment by tmadlener** [comment]
I would also really appreciate that and volunteer for testing.

Just for completeness: I got the the example app from angular to run, but things started to fail for me once I tried to added a new component for the experiment. However, that could also just be me being stupid and not knowing enough about angular to fix a few potentially smaller issues or misunderstanding the instructions.

**Comment by DraTeots** [comment]
Here is the PR #668

**Comment by EdwardMoyse** [comment]
Again, apologies for the long delay, but I think we can close this now (thanks to @DraTeots )
