### ISSUE TITLE
popup windows not showing

### ISSUE THREAD

**Issue by davzuliani** [HSF/phoenix#676]
It is a very minor problem, but when I try to clic on buttons in the UI menu, say "Geometry Clipping" the popup window does not show up.

I manage to follow the guide, and I'm able to see the geometry and all, but this issue doesn't allow me to perform some options (where possible).

**Comment by DraTeots** [comment]
Could you check if there is some error outputs in the development console of the browser? (ctrl+shift+I -> Console, reboot the page and click those buttons)

**Comment by davzuliani** [comment]
> Could you check if there is some error outputs in the development console of the browser? (ctrl+shift+I -> Console, reboot the page and click those buttons)

Right, my bad for not trying before. This is what comes out:

```
ERROR IN PHOENIX APP 
 Error: NG05105: Unexpected synthetic listener @transformMenu.start found. Please make sure that:
  - Either `BrowserAnimationsModule` or `NoopAnimationsModule` are imported in your application.
  - There is corresponding configuration for the animation named `@transformMenu.start` defined in the `animations` field of the `@Component` decorator (see https://angular.io/api/core/Component#animations).
    at checkNoSyntheticProp (platform-browser.mjs:760:11)
    at NoneEncapsulationDomRenderer.listen (platform-browser.mjs:724:86)
    at listenerInternal (core.mjs:25599:40)
    at ɵɵlistener (core.mjs:25480:5)
    at MatMenu_ng_template_0_Template (menu.mjs:46:6)
    at executeTemplate (core.mjs:11268:9)
    at renderView (core.mjs:12470:13)
    at createAndRenderEmbeddedLView (core.mjs:12540:9)
    at TemplateRef2.createEmbeddedViewImpl (core.mjs:13393:31)
    at ViewContainerRef2.createEmbeddedView (core.mjs:16191:37)
```

**Comment by DraTeots** [comment]
Ah... As I remember it correctly, you should call `provideAnimations()` in your app configuration. 

So go to `src/app/app.config.ts` and add there: 

```ts
// imports section
//...
import {provideAnimations} from "@angular/platform-browser/animations";

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideAnimations(),    // <= add this line
  // ...
  ]
};
```

Please, let us know if it works or not!

**Comment by davzuliani** [comment]
Yes, that worked fine, thank you very much!!!
