### ISSUE TITLE
Disabling geometry doesn't disable it for selection

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#77]
I was trying to select a jet and this was difficult because I kept selecting "invisible" geometry instead. Manually hiding all geometry seems to make no difference.

I also noticed that with "object selection" enabled, the performance drops - my guess is the hidden geometry is still being highlighted.

**Comment by EdwardMoyse** [comment]
If I manually **remove** the geometry, then it works (and performance is great!). Even better, highlighting Jets works (tracks and clusters however still not, but that's for another ticket!)

**Comment by 9inpachi** [comment]
Interesting.
This is actually true the other way around too. When event data is hidden and geometry is shown, we can end up selecting event data.

Edward, I will look into this.

**Comment by emiliocortina** [comment]
I had never thought of that. It was pretty straightforward to solve so I've just uploaded a fix on #76.
Let me know if there is anything wrong.

**Comment by 9inpachi** [comment]
That looks good.
I was looking into the touchmove/mousemove event. :)

**Comment by emiliocortina** [comment]
> That looks good.
> I was looking into the touchmove/mousemove event. :)

Thanks for checking, closing this then.
