### ISSUE TITLE
Resizing window scales conte nt

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#85]
I don't think we want this - the aspect ratio should be fixed, no matter the size of the viewport.

<img width="1087" alt="Scaled" src="https://user-images.githubusercontent.com/6764617/83740529-40ef1f80-a657-11ea-8ad0-b660f6ff98ae.png">

**Comment by EdwardMoyse** [comment]
Ah - just noticed that this ONLY seems to happen on chrome (macos) and not on Firefox or Safari. I also get black mode by default on chrome, whereas it's light on the others. Perhaps I've got an issue locally ... I'll have a look.

**Comment by 9inpachi** [comment]
This does exist on Chrome in Windows.

Since this comes under GUI, I will push a fix in wip-gui branch of my fork. Assigning it to myself.
