### ISSUE TITLE
Improve deployment

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#88]
We should probably tag a version, then deploy this?

It would be great to automate this - so someone with sufficient permission could do it through the web interface.

**Comment by 9inpachi** [comment]
> We should probably tag a version, then deploy this?

I would say, yes. It's probably worth it to start releasing Phoenix in versions with major and minor indicators (1.major.minor - 1.0.0 for the first release).

> It would be great to automate this - so someone with sufficient permission could do it through the web interface.

I will take a look at GitHub actions for this.

**Comment by EdwardMoyse** [comment]
It would be great to have releases as produced by threejs:
https://github.com/mrdoob/three.js/releases

**Comment by 9inpachi** [comment]
Hi Ed,

I would need to know which actions should deploy and release the application.

We could either:
1. Deploy on web and release the application by pushing to a new tag (both occur by pushing to a tag)
2. Deploy on web by pushing to master branch (no release)
3. Deploy on web by pushing to master branch AND release the application by pushing to a new tag (both are separate)
4. Deploy on web by pushing to master branch AND release manually through the GitHub interface

I would say we separate the both release and deployment (3) since we don't want to release for every web version we deploy.

What do you say?

**Comment by 9inpachi** [comment]
So I have been testing this out a lot and improving the deployment and release GitHub action and I think the 4th options makes most sense. We shouldn't have an automated release.
Releasing is actually as simple as:
```sh
git tag v1.0 master
git push v1.0
```
But i think it's better if we do it manually through the GitHub interface as it doesn't make much sense to just package and release the app with an automated action.

**Comment by EdwardMoyse** [comment]
H Fawad

I definitely agree with not having an automated release, and I also think
releasing a version and pushing a new version to the web server are
different actions (we might want to update the web version before making a
new release, for example). But ideally it’d be great to be able to click a
button to update the demo/web version. Is this what you mean?

Cheers,

Ed

**Comment by 9inpachi** [comment]
> But ideally it’d be great to be able to click a
button to update the demo/web version. Is this what you mean?

I don't think the GitHub interface allows us to create something like that. But [THIS](https://medium.com/@christinavhastenrath/how-to-run-github-actions-manually-afebbe77d325) might be possible through GitHub actions. If you mean a button on the Phoenix website then I think we will need to use the GitHub API but I don't have any idea if it supports something like our use case.
I thought of continuous delivery and I worked on a GitHub action script to deploy with push ([here](https://github.com/9inpachi/phoenix/tree/wip-deployment)).

**Comment by 9inpachi** [comment]
@EdwardMoyse About deployment, I think it would be good to deploy automatically with a "pull request". Having pull requests for each new feature / fix helps in tracking them better as well.

**Comment by EdwardMoyse** [comment]
So you mean each accepted PR would lead to a deployment? This might be simplest I suppose - I worry a little that it means we can't easily have a 'production' version which we keep stable. Though this will matter less once experiments have their own deployed versions....

**Comment by 9inpachi** [comment]
> I worry a little that it means we can't easily have a 'production' version which we keep stable.

That is true. I just haven't work on deployment so much to know an optimal way to do it for a project like Phoenix.
But if it's a matter of stability and versioning, I think what would work better is to have production only when releasing a new version of the event display and the app. That is to have a single command in the root repository, something like `npm run deploy` or using yarn or some other tool like [lerna](https://github.com/lerna/lerna) which will perform all the operations for us.

* Deploy the app
* Deploy the API docs for event display
* Publish a new version of both the event display and the app to npm

This will only take place for releases, which can either be minor or major (depending on the npm version of packages). And releases will be done after some time period and not so often.

WDYT?

**Comment by EdwardMoyse** [comment]
Yes, this sounds like a very good solution. I would say, we should tag the version at the same time. That way it can be marked as a release inside github too.

**Comment by 9inpachi** [comment]
Yes, indeed.

I will see how we can authenticate for the release.

**Comment by 9inpachi** [comment]
Done with 9fa150b9f05f0a51d8bd5add3b682033179385b8 and 399ac77703c326c1b4523146b23688a12ec97cc0.
